// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:32:31

// !!! ATTENTION !!!
// This is an auto-generated file with dialog box widget prototype declaration and initialization.
// Include it into your dialog box widget class header file and derive your widget from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// Also add service(if your widget need one) derived from service prototype below(do not forget to call parent class methods wher overwriting methods).
// For example:
//     DialogBoxReplaceProto.h:
//         #include "Nitisa/Core/Consts.h" // DesignDPI constant is declared here
//         #include "Nitisa/Image/Color.h" // Color declaration is here
//         #include "IDialogBoxReplaceProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CDialogBoxReplaceProto : public IDialogBoxReplaceProto // Derive your widget from class from this file
//                 {
//                 private: // Private members for handling widget logic
//                     Color m_sBackgroundColor; // Store background color
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     // IDialogBox's abstract methods re-declaration
//                     Color getBackgroundColor() override;
//                     // Add other abstract methods needed to be implemented
//
//                     CDialogBoxReplaceProto(); // Declare constructor
//                 };
//             }
//         }
//
//     DialogBoxReplaceProto.cpp:
//         #include "DialogBoxReplaceProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CDialogBoxReplaceProto::CDialogBoxReplaceProto(): // Implement constructor of your widget
//                     IDialogBoxReplaceProto(L"DialogBoxReplaceProto", true, true, false, false, DesignDPI) // Here you may add your service implementation as the latest parameter
//                 {
//                     // Insert your code here
//                 }
//
//                 void CDialogBoxReplaceProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//
//                 Color CDialogBoxReplaceProto::getBackgroundColor() // Implement IDialogBox's getBackgroundColor() methods
//                 {
//                     return m_sBackgroundColor;
//                 }
//                 // Implement other IDialogBox's abstract methods
//             }
//         }

#pragma once

#include "Nitisa/Core/Consts.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/CheckBox/CheckBox.h"
#include "../../Controls/DialogBoxEx/DialogBoxEx.h"
#include "../../Controls/DialogBoxEx/DialogBoxExService.h"
#include "../../Controls/Edit/Edit.h"
#include "../../Controls/GroupBox/GroupBox.h"
#include "../../Controls/Label/Label.h"
#include "../../Controls/RadioButton/RadioButton.h"

namespace nitisa
{
	class IControl;
	class IDialogBoxService;
	class IForm;

	namespace standard
	{
		class IDialogBoxReplaceProto : public CDialogBoxEx
		{
		public:
			class IDialogBoxReplaceProtoService: public CDialogBoxExService
			{
			private:
				IDialogBoxReplaceProto *m_pControl;
			public:
				void NotifyOnAttach() override
				{
					CDialogBoxExService::NotifyOnAttach();
					if (m_pControl->getForm())
					{
					}
				}

				void NotifyOnDetaching() override
				{
					CDialogBoxExService::NotifyOnDetaching();
				}

				IDialogBoxReplaceProtoService(IDialogBoxReplaceProto *control) : CDialogBoxExService(control),
					m_pControl{ control }
				{

				}
			};
		protected:
			// Controls
			CLabel *m_pLabel1;
			CLabel *m_pLabel2;
			CEdit *m_pEditText;
			CEdit *m_pEditReplace;
			CCheckBox *m_pCheckBoxWords;
			CCheckBox *m_pCheckBoxCase;
			CGroupBox *m_pGroupBox1;
			CRadioButton *m_pRadioButtonUp;
			CRadioButton *m_pRadioButtonDown;
			CRadioButton *m_pRadioButtonSelection;
			CButton *m_pButtonReplace;
			CButton *m_pButtonReplaceAll;
			CButton *m_pButtonCancel;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormReplaceProto_OnKeyUp(IControl *sender, const MessageKey &m, bool &processed) = 0;
			virtual void EditText_OnKeyUp(IControl *sender, const MessageKey &m, bool &processed) = 0;
			virtual void EditText_OnChange(IControl *sender) = 0;
			virtual void EditReplace_OnKeyUp(IControl *sender, const MessageKey &m, bool &processed) = 0;
			virtual void ButtonReplace_OnClick(IControl *sender) = 0;
			virtual void ButtonReplaceAll_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pLabel1 = new CLabel(this);
				m_pLabel1->setName(L"Label1");
				m_pLabel2 = new CLabel(this);
				m_pLabel2->setName(L"Label2");
				m_pEditText = new CEdit(this);
				m_pEditText->setName(L"EditText");
				m_pEditReplace = new CEdit(this);
				m_pEditReplace->setName(L"EditReplace");
				m_pCheckBoxWords = new CCheckBox(this);
				m_pCheckBoxWords->setName(L"CheckBoxWords");
				m_pCheckBoxCase = new CCheckBox(this);
				m_pCheckBoxCase->setName(L"CheckBoxCase");
				m_pGroupBox1 = new CGroupBox(this);
				m_pGroupBox1->setName(L"GroupBox1");
				m_pRadioButtonUp = new CRadioButton(m_pGroupBox1);
				m_pRadioButtonUp->setName(L"RadioButtonUp");
				m_pRadioButtonDown = new CRadioButton(m_pGroupBox1);
				m_pRadioButtonDown->setName(L"RadioButtonDown");
				m_pRadioButtonSelection = new CRadioButton(m_pGroupBox1);
				m_pRadioButtonSelection->setName(L"RadioButtonSelection");
				m_pButtonReplace = new CButton(this);
				m_pButtonReplace->setName(L"ButtonReplace");
				m_pButtonReplaceAll = new CButton(this);
				m_pButtonReplaceAll->setName(L"ButtonReplaceAll");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");

				// Initialize controls
				m_pLabel1->setName(L"Label1");
				m_pLabel1->getTransform()->Translate(8.0f, 12.0f, 0.0f);
				m_pLabel1->setCaption(UTF8ToString("Find what:"));

				m_pLabel2->setName(L"Label2");
				m_pLabel2->getTransform()->Translate(9.0f, 34.0f, 0.0f);
				m_pLabel2->setCaption(UTF8ToString("Replace with:"));

				m_pEditText->setName(L"EditText");
				m_pEditText->getTransform()->Translate(104.0f, 8.0f, 0.0f);
				m_pEditText->setSize(PointF{ 352.0f, 20.0f });
				m_pEditText->setTabOrder(3);
				m_pEditText->setText(UTF8ToString(""));
				m_pEditText->OnKeyUp = [](IControl *sender, const MessageKey &m, bool &processed)->void { parent<IDialogBoxReplaceProto*, false>(sender)->EditText_OnKeyUp(sender, m, processed); };
				m_pEditText->OnChange = [](IControl *sender)->void { parent<IDialogBoxReplaceProto*, false>(sender)->EditText_OnChange(sender); };

				m_pEditReplace->setName(L"EditReplace");
				m_pEditReplace->getTransform()->Translate(104.0f, 32.0f, 0.0f);
				m_pEditReplace->setSize(PointF{ 352.0f, 20.0f });
				m_pEditReplace->setTabOrder(4);
				m_pEditReplace->setText(UTF8ToString(""));
				m_pEditReplace->OnKeyUp = [](IControl *sender, const MessageKey &m, bool &processed)->void { parent<IDialogBoxReplaceProto*, false>(sender)->EditReplace_OnKeyUp(sender, m, processed); };

				m_pCheckBoxWords->setName(L"CheckBoxWords");
				m_pCheckBoxWords->getTransform()->Translate(8.0f, 73.0f, 0.0f);
				m_pCheckBoxWords->setTabOrder(5);
				m_pCheckBoxWords->setCaption(UTF8ToString("Match whole words"));

				m_pCheckBoxCase->setName(L"CheckBoxCase");
				m_pCheckBoxCase->getTransform()->Translate(8.0f, 96.0f, 0.0f);
				m_pCheckBoxCase->setTabOrder(6);
				m_pCheckBoxCase->setCaption(UTF8ToString("Match case"));

				m_pGroupBox1->setName(L"GroupBox1");
				m_pGroupBox1->getTransform()->Translate(192.0f, 56.0f, 0.0f);
				m_pGroupBox1->setSize(PointF{ 265.0f, 57.0f });
				m_pGroupBox1->setCaption(UTF8ToString("Direction"));
				m_pGroupBox1->setUseMask(false);

				m_pRadioButtonUp->setName(L"RadioButtonUp");
				m_pRadioButtonUp->getTransform()->Translate(16.0f, 24.0f, 0.0f);
				m_pRadioButtonUp->setTabOrder(8);
				m_pRadioButtonUp->setCaption(UTF8ToString("Up"));

				m_pRadioButtonDown->setName(L"RadioButtonDown");
				m_pRadioButtonDown->getTransform()->Translate(88.0f, 24.0f, 0.0f);
				m_pRadioButtonDown->setTabOrder(9);
				m_pRadioButtonDown->setCaption(UTF8ToString("Down"));
				m_pRadioButtonDown->setChecked(true);

				m_pRadioButtonSelection->setName(L"RadioButtonSelection");
				m_pRadioButtonSelection->getTransform()->Translate(168.0f, 24.0f, 0.0f);
				m_pRadioButtonSelection->setTabOrder(10);
				m_pRadioButtonSelection->setCaption(UTF8ToString("Selection"));

				m_pButtonReplace->setName(L"ButtonReplace");
				m_pButtonReplace->getTransform()->Translate(464.0f, 8.0f, 0.0f);
				m_pButtonReplace->setTabOrder(11);
				m_pButtonReplace->setEnabled(false);
				m_pButtonReplace->setCaption(UTF8ToString("Replace"));
				m_pButtonReplace->OnClick = [](IControl *sender)->void { parent<IDialogBoxReplaceProto*, false>(sender)->ButtonReplace_OnClick(sender); };

				m_pButtonReplaceAll->setName(L"ButtonReplaceAll");
				m_pButtonReplaceAll->getTransform()->Translate(464.0f, 40.0f, 0.0f);
				m_pButtonReplaceAll->setTabOrder(12);
				m_pButtonReplaceAll->setEnabled(false);
				m_pButtonReplaceAll->setCaption(UTF8ToString("Replace All"));
				m_pButtonReplaceAll->OnClick = [](IControl *sender)->void { parent<IDialogBoxReplaceProto*, false>(sender)->ButtonReplaceAll_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(464.0f, 72.0f, 0.0f);
				m_pButtonCancel->setTabOrder(13);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { parent<IDialogBoxReplaceProto*, false>(sender)->ButtonCancel_OnClick(sender); };


			}

		public:
			IDialogBoxReplaceProto(const String &class_name, const bool accept_form, const bool accept_control, const bool accept_focus, const bool tab_stop, const Point &design_dpi = DesignDPI, IDialogBoxService *service = nullptr) :
				CDialogBoxEx(class_name, accept_form, accept_control, accept_focus, tab_stop, design_dpi, service ? service : new IDialogBoxReplaceProtoService(this)),
				m_pLabel1{ nullptr },
				m_pLabel2{ nullptr },
				m_pEditText{ nullptr },
				m_pEditReplace{ nullptr },
				m_pCheckBoxWords{ nullptr },
				m_pCheckBoxCase{ nullptr },
				m_pGroupBox1{ nullptr },
				m_pRadioButtonUp{ nullptr },
				m_pRadioButtonDown{ nullptr },
				m_pRadioButtonSelection{ nullptr },
				m_pButtonReplace{ nullptr },
				m_pButtonReplaceAll{ nullptr },
				m_pButtonCancel{ nullptr }
			{
				CLockRepaint lock(this);
				setName(L"DialogBoxReplaceProto");
				setCaption(UTF8ToString("Replace"));
				setClientSize(Point{ 576, 122 });
				setWindowPosition(WindowPosition::MainFormCenter);
				setState(WindowState::Hidden);
				setHasMaximizeBox(false);
				setHasMinimizeBox(false);
				setHasSizeBox(false);
				Initialize();
				OnKeyUp = [](IControl *sender, const MessageKey &m, bool &processed)->void { cast<IDialogBoxReplaceProto*>(sender)->FormReplaceProto_OnKeyUp(sender, m, processed); };
			}

			IComponent *getComponent(const String &name)
			{
				return nullptr;
			}

			IControl *FindControl(const String &name, IControl *exclude = nullptr) override
			{
				if (name == L"Label1" && m_pLabel1 != exclude)
					return m_pLabel1;
				if (name == L"Label2" && m_pLabel2 != exclude)
					return m_pLabel2;
				if (name == L"EditText" && m_pEditText != exclude)
					return m_pEditText;
				if (name == L"EditReplace" && m_pEditReplace != exclude)
					return m_pEditReplace;
				if (name == L"CheckBoxWords" && m_pCheckBoxWords != exclude)
					return m_pCheckBoxWords;
				if (name == L"CheckBoxCase" && m_pCheckBoxCase != exclude)
					return m_pCheckBoxCase;
				if (name == L"GroupBox1" && m_pGroupBox1 != exclude)
					return m_pGroupBox1;
				if (name == L"RadioButtonUp" && m_pRadioButtonUp != exclude)
					return m_pRadioButtonUp;
				if (name == L"RadioButtonDown" && m_pRadioButtonDown != exclude)
					return m_pRadioButtonDown;
				if (name == L"RadioButtonSelection" && m_pRadioButtonSelection != exclude)
					return m_pRadioButtonSelection;
				if (name == L"ButtonReplace" && m_pButtonReplace != exclude)
					return m_pButtonReplace;
				if (name == L"ButtonReplaceAll" && m_pButtonReplaceAll != exclude)
					return m_pButtonReplaceAll;
				if (name == L"ButtonCancel" && m_pButtonCancel != exclude)
					return m_pButtonCancel;
				return nullptr;
			}

		};
	}
}

