// This file is a part of Nitisa framework
// Copyright © 2022 Nitisa. All rights reserved.
// Author: Dimitry Lysenko
// Site: http://nitisa.com
// Download: http://nitisa.com/downloads
// Documentation: http://nitisa.com/documentation
// License: http://nitisa.com/site/license

#pragma once

// Controls
#include "Controls/EventEditor/EventEditor.h"
#include "Controls/EventEditor/EventEditorService.h"
#include "Controls/FormEditor/FormEditor.h"
#include "Controls/FormEditor/FormEditorService.h"
#include "Controls/FormView/FormView.h"
#include "Controls/FormView/FormViewService.h"
#include "Controls/HierarchyEditor/HierarchyEditor.h"
#include "Controls/HierarchyEditor/HierarchyEditorService.h"
#include "Controls/HierarchyEditor/ListItemHierarchyEditor.h"
#include "Controls/PropertyEditor/PropertyEditor.h"
#include "Controls/PropertyEditor/PropertyEditorService.h"
#include "Controls/ViewCross/ViewCross.h"
#include "Controls/ViewCross/ViewCrossService.h"
#include "Controls/ViewH1H2/ViewH1H2.h"
#include "Controls/ViewH1H2/ViewH1H2Service.h"
#include "Controls/ViewH1H2L/ViewH1H2L.h"
#include "Controls/ViewH1H2L/ViewH1H2LService.h"
#include "Controls/ViewH1H2R/ViewH1H2R.h"
#include "Controls/ViewH1H2R/ViewH1H2RService.h"
#include "Controls/ViewH1H3/ViewH1H3.h"
#include "Controls/ViewH1H3/ViewH1H3Service.h"
#include "Controls/ViewH2/ViewH2.h"
#include "Controls/ViewH2/ViewH2Service.h"
#include "Controls/ViewH2H1/ViewH2H1.h"
#include "Controls/ViewH2H1/ViewH2H1Service.h"
#include "Controls/ViewH2H2/ViewH2H2.h"
#include "Controls/ViewH2H2/ViewH2H2Service.h"
#include "Controls/ViewH2LH1/ViewH2LH1.h"
#include "Controls/ViewH2LH1/ViewH2LH1Service.h"
#include "Controls/ViewH2RH1/ViewH2RH1.h"
#include "Controls/ViewH2RH1/ViewH2RH1Service.h"
#include "Controls/ViewH3/ViewH3.h"
#include "Controls/ViewH3/ViewH3Service.h"
#include "Controls/ViewH3H1/ViewH3H1.h"
#include "Controls/ViewH3H1/ViewH3H1Service.h"
#include "Controls/ViewV1V2/ViewV1V2.h"
#include "Controls/ViewV1V2/ViewV1V2Service.h"
#include "Controls/ViewV1V2B/ViewV1V2B.h"
#include "Controls/ViewV1V2B/ViewV1V2BService.h"
#include "Controls/ViewV1V2T/ViewV1V2T.h"
#include "Controls/ViewV1V2T/ViewV1V2TService.h"
#include "Controls/ViewV1V3/ViewV1V3.h"
#include "Controls/ViewV1V3/ViewV1V3Service.h"
#include "Controls/ViewV2/ViewV2.h"
#include "Controls/ViewV2/ViewV2Service.h"
#include "Controls/ViewV2BV1/ViewV2BV1.h"
#include "Controls/ViewV2BV1/ViewV2BV1Service.h"
#include "Controls/ViewV2TV1/ViewV2TV1.h"
#include "Controls/ViewV2TV1/ViewV2TV1Service.h"
#include "Controls/ViewV2V1/ViewV2V1.h"
#include "Controls/ViewV2V1/ViewV2V1Service.h"
#include "Controls/ViewV2V2/ViewV2V2.h"
#include "Controls/ViewV2V2/ViewV2V2Service.h"
#include "Controls/ViewV3/ViewV3.h"
#include "Controls/ViewV3/ViewV3Service.h"
#include "Controls/ViewV3V1/ViewV3V1.h"
#include "Controls/ViewV3V1/ViewV3V1Service.h"
#include "Controls/IEventEditor.h"
#include "Controls/IFormEditor.h"
#include "Controls/IFormView.h"
#include "Controls/IHierarchyEditor.h"
#include "Controls/IPropertyEditor.h"
#include "Controls/IViewCross.h"
#include "Controls/IViewH1H2.h"
#include "Controls/IViewH1H2L.h"
#include "Controls/IViewH1H2R.h"
#include "Controls/IViewH1H3.h"
#include "Controls/IViewH2.h"
#include "Controls/IViewH2H1.h"
#include "Controls/IViewH2H2.h"
#include "Controls/IViewH2LH1.h"
#include "Controls/IViewH2RH1.h"
#include "Controls/IViewH3.h"
#include "Controls/IViewH3H1.h"
#include "Controls/IViewV1V2.h"
#include "Controls/IViewV1V2B.h"
#include "Controls/IViewV1V2T.h"
#include "Controls/IViewV1V3.h"
#include "Controls/IViewV2.h"
#include "Controls/IViewV2BV1.h"
#include "Controls/IViewV2TV1.h"
#include "Controls/IViewV2V1.h"
#include "Controls/IViewV2V2.h"
#include "Controls/IViewV3.h"
#include "Controls/IViewV3V1.h"

// Interfaces
#include "Interfaces/IViewControl.h"

// Package controls
#include "Package/Controls/EventEditor/EventEditorEventList.h"
#include "Package/Controls/EventEditor/EventEditorPropertyList.h"
#include "Package/Controls/EventEditor/PackageEventEditor.h"
#include "Package/Controls/FormEditor/FormEditorEventList.h"
#include "Package/Controls/FormEditor/FormEditorPropertyList.h"
#include "Package/Controls/FormEditor/PackageFormEditor.h"
#include "Package/Controls/FormView/FormViewEventList.h"
#include "Package/Controls/FormView/FormViewPropertyList.h"
#include "Package/Controls/FormView/PackageFormView.h"
#include "Package/Controls/HierarchyEditor/HierarchyEditorEventList.h"
#include "Package/Controls/HierarchyEditor/HierarchyEditorPropertyList.h"
#include "Package/Controls/HierarchyEditor/PackageHierarchyEditor.h"
#include "Package/Controls/PropertyEditor/PropertyEditorEventList.h"
#include "Package/Controls/PropertyEditor/PropertyEditorPropertyList.h"
#include "Package/Controls/PropertyEditor/PackagePropertyEditor.h"

#include "Package/Controls/ViewCross/PackageViewCross.h"
#include "Package/Controls/ViewCross/ViewCrossEventList.h"
#include "Package/Controls/ViewCross/ViewCrossPropertyList.h"

#include "Package/Controls/ViewH1H2/PackageViewH1H2.h"
#include "Package/Controls/ViewH1H2/ViewH1H2EventList.h"
#include "Package/Controls/ViewH1H2/ViewH1H2PropertyList.h"

#include "Package/Controls/ViewH1H2L/PackageViewH1H2L.h"
#include "Package/Controls/ViewH1H2L/ViewH1H2LEventList.h"
#include "Package/Controls/ViewH1H2L/ViewH1H2LPropertyList.h"

#include "Package/Controls/ViewH1H2R/PackageViewH1H2R.h"
#include "Package/Controls/ViewH1H2R/ViewH1H2REventList.h"
#include "Package/Controls/ViewH1H2R/ViewH1H2RPropertyList.h"

#include "Package/Controls/ViewH1H3/PackageViewH1H3.h"
#include "Package/Controls/ViewH1H3/ViewH1H3EventList.h"
#include "Package/Controls/ViewH1H3/ViewH1H3PropertyList.h"

#include "Package/Controls/ViewH2/PackageViewH2.h"
#include "Package/Controls/ViewH2/ViewH2EventList.h"
#include "Package/Controls/ViewH2/ViewH2PropertyList.h"

#include "Package/Controls/ViewH2H1/PackageViewH2H1.h"
#include "Package/Controls/ViewH2H1/ViewH2H1EventList.h"
#include "Package/Controls/ViewH2H1/ViewH2H1PropertyList.h"

#include "Package/Controls/ViewH2H2/PackageViewH2H2.h"
#include "Package/Controls/ViewH2H2/ViewH2H2EventList.h"
#include "Package/Controls/ViewH2H2/ViewH2H2PropertyList.h"

#include "Package/Controls/ViewH2LH1/PackageViewH2LH1.h"
#include "Package/Controls/ViewH2LH1/ViewH2LH1EventList.h"
#include "Package/Controls/ViewH2LH1/ViewH2LH1PropertyList.h"

#include "Package/Controls/ViewH2RH1/PackageViewH2RH1.h"
#include "Package/Controls/ViewH2RH1/ViewH2RH1EventList.h"
#include "Package/Controls/ViewH2RH1/ViewH2RH1PropertyList.h"

#include "Package/Controls/ViewH3/PackageViewH3.h"
#include "Package/Controls/ViewH3/ViewH3EventList.h"
#include "Package/Controls/ViewH3/ViewH3PropertyList.h"

#include "Package/Controls/ViewH3H1/PackageViewH3H1.h"
#include "Package/Controls/ViewH3H1/ViewH3H1EventList.h"
#include "Package/Controls/ViewH3H1/ViewH3H1PropertyList.h"

#include "Package/Controls/ViewV1V2/PackageViewV1V2.h"
#include "Package/Controls/ViewV1V2/ViewV1V2EventList.h"
#include "Package/Controls/ViewV1V2/ViewV1V2PropertyList.h"

#include "Package/Controls/ViewV1V2B/PackageViewV1V2B.h"
#include "Package/Controls/ViewV1V2B/ViewV1V2BEventList.h"
#include "Package/Controls/ViewV1V2B/ViewV1V2BPropertyList.h"

#include "Package/Controls/ViewV1V2T/PackageViewV1V2T.h"
#include "Package/Controls/ViewV1V2T/ViewV1V2TEventList.h"
#include "Package/Controls/ViewV1V2T/ViewV1V2TPropertyList.h"

#include "Package/Controls/ViewV1V3/PackageViewV1V3.h"
#include "Package/Controls/ViewV1V3/ViewV1V3EventList.h"
#include "Package/Controls/ViewV1V3/ViewV1V3PropertyList.h"

#include "Package/Controls/ViewV2/PackageViewV2.h"
#include "Package/Controls/ViewV2/ViewV2EventList.h"
#include "Package/Controls/ViewV2/ViewV2PropertyList.h"

#include "Package/Controls/ViewV2BV1/PackageViewV2BV1.h"
#include "Package/Controls/ViewV2BV1/ViewV2BV1EventList.h"
#include "Package/Controls/ViewV2BV1/ViewV2BV1PropertyList.h"

#include "Package/Controls/ViewV2TV1/PackageViewV2TV1.h"
#include "Package/Controls/ViewV2TV1/ViewV2TV1EventList.h"
#include "Package/Controls/ViewV2TV1/ViewV2TV1PropertyList.h"

#include "Package/Controls/ViewV2V1/PackageViewV2V1.h"
#include "Package/Controls/ViewV2V1/ViewV2V1EventList.h"
#include "Package/Controls/ViewV2V1/ViewV2V1PropertyList.h"

#include "Package/Controls/ViewV2V2/PackageViewV2V2.h"
#include "Package/Controls/ViewV2V2/ViewV2V2EventList.h"
#include "Package/Controls/ViewV2V2/ViewV2V2PropertyList.h"

#include "Package/Controls/ViewV3/PackageViewV3.h"
#include "Package/Controls/ViewV3/ViewV3EventList.h"
#include "Package/Controls/ViewV3/ViewV3PropertyList.h"

#include "Package/Controls/ViewV3V1/PackageViewV3V1.h"
#include "Package/Controls/ViewV3V1/ViewV3V1EventList.h"
#include "Package/Controls/ViewV3V1/ViewV3V1PropertyList.h"

// Package
#include "Package/PackageIde.h"
#include "Package/PackageIdeService.h"