// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:33:51

// !!! ATTENTION !!!
// This is an auto-generated file with form declaration and initialization.
// Include it into your form class header file and derive your form from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// For example:
//     FormHotkeyProto.h:
//         #include "IFormHotkeyProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CFormHotkeyProto : public IFormHotkeyProto // Derive your form from class from this file
//                 {
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     CFormHotkeyProto(); // Declare constructor
//                 };
//             }
//         }
//
//     FormHotkeyProto.cpp:
//         #include "Standard/Platform/Windows/Window.h" // Include required platform window management class
//         #include "Standard/Platform/Windows/OpenGL/Renderer.h" // Include required renderer
//         #include "FormHotkeyProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CFormHotkeyProto::CFormHotkeyProto(): // Implement constructor of your form
//                     IFormHotkeyProto(new standard::windows::CWindow(), new standard::windows::opengl::CRenderer(false, 0))
//                 {
//                     // Insert your code here
//                 }
//
//                 void CFormHotkeyProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//             }
//         }


#pragma once

#include "Nitisa/Core/Form.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/IFormService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/CheckBox/CheckBox.h"
#include "../../Controls/HotKey/HotKey.h"
#include "../../Controls/Label/Label.h"

namespace nitisa
{
	class IControl;
	class IRenderer;
	class IWindow;
	struct CreateParams;

	namespace standard
	{
		class IFormHotkeyProto : public CForm
		{
		protected:
			// Controls
			CLabel *m_pLabelHotkey;
			CHotKey *m_pHotKey;
			CCheckBox *m_pCheckBoxDown;
			CButton *m_pButtonOk;
			CButton *m_pButtonCancel;
			CButton *m_pButtonEmpty;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;
			virtual void ButtonEmpty_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pLabelHotkey = new CLabel(this);
				m_pLabelHotkey->setName(L"LabelHotkey");
				m_pHotKey = new CHotKey(this);
				m_pHotKey->setName(L"HotKey");
				m_pCheckBoxDown = new CCheckBox(this);
				m_pCheckBoxDown->setName(L"CheckBoxDown");
				m_pButtonOk = new CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonEmpty = new CButton(this);
				m_pButtonEmpty->setName(L"ButtonEmpty");

				// Initialize controls
				m_pLabelHotkey->setName(L"LabelHotkey");
				m_pLabelHotkey->getTransform()->Translate(8.0f, 8.0f, 0.0f);
				m_pLabelHotkey->setCaption(UTF8ToString("Click on field below and press key combination you want"));

				m_pHotKey->setName(L"HotKey");
				m_pHotKey->getTransform()->Translate(8.0f, 28.0f, 0.0f);
				m_pHotKey->setSize(PointF{ 175.0f, 20.0f });
				m_pHotKey->setTabOrder(2);

				m_pCheckBoxDown->setName(L"CheckBoxDown");
				m_pCheckBoxDown->getTransform()->Translate(187.0f, 32.0f, 0.0f);
				m_pCheckBoxDown->setTabOrder(3);
				m_pCheckBoxDown->setCaption(UTF8ToString("Is hotkey down(up otherwise)?"));

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(79.0f, 52.0f, 0.0f);
				m_pButtonOk->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonOk->setTabOrder(4);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { cast<IFormHotkeyProto*>(sender->getForm())->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(151.0f, 52.0f, 0.0f);
				m_pButtonCancel->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonCancel->setTabOrder(5);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { cast<IFormHotkeyProto*>(sender->getForm())->ButtonCancel_OnClick(sender); };

				m_pButtonEmpty->setName(L"ButtonEmpty");
				m_pButtonEmpty->getTransform()->Translate(223.0f, 52.0f, 0.0f);
				m_pButtonEmpty->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonEmpty->setTabOrder(6);
				m_pButtonEmpty->setCaption(UTF8ToString("No hotkey"));
				m_pButtonEmpty->OnClick = [](IControl *sender)->void { cast<IFormHotkeyProto*>(sender->getForm())->ButtonEmpty_OnClick(sender); };


			}

		public:
			IFormHotkeyProto(IWindow *window, IRenderer *renderer, const String &class_name = L"FormHotkeyProto", const CreateParams *params = nullptr) :
				CForm(class_name, nullptr, renderer, params),
				m_pLabelHotkey{ nullptr },
				m_pHotKey{ nullptr },
				m_pCheckBoxDown{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr },
				m_pButtonEmpty{ nullptr }
			{
				if (window)
				{
					CLockRepaint lock(this);
					setName(L"FormHotkeyProto");
					setCaption(UTF8ToString("Hotkey"));
					setClientSize(Point{ 370, 83 });
					setState(WindowState::Hidden);
					setWindowPosition(WindowPosition::MainFormCenter);
					setHasMaximizeBox(false);
					setHasMinimizeBox(false);
					setHasSizeBox(false);
					QueryService()->setWindow(window);
					Application->QueryService()->Add(this);
					Initialize();
					Repaint(Rect{ 0, 0, 0, 0 }, true);
				}
			}
		};
	}
}
