// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:32:52

// !!! ATTENTION !!!
// This is an auto-generated file with form declaration and initialization.
// Include it into your form class header file and derive your form from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// For example:
//     FormBoolArrayProto.h:
//         #include "IFormBoolArrayProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CFormBoolArrayProto : public IFormBoolArrayProto // Derive your form from class from this file
//                 {
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     CFormBoolArrayProto(); // Declare constructor
//                 };
//             }
//         }
//
//     FormBoolArrayProto.cpp:
//         #include "Standard/Platform/Windows/Window.h" // Include required platform window management class
//         #include "Standard/Platform/Windows/OpenGL/Renderer.h" // Include required renderer
//         #include "FormBoolArrayProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CFormBoolArrayProto::CFormBoolArrayProto(): // Implement constructor of your form
//                     IFormBoolArrayProto(new standard::windows::CWindow(), new standard::windows::opengl::CRenderer(false, 0))
//                 {
//                     // Insert your code here
//                 }
//
//                 void CFormBoolArrayProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//             }
//         }


#pragma once

#include "Nitisa/Core/Form.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/IFormService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/Label/Label.h"
#include "../../Controls/ListBox/CustomListBox.h"
#include "../../Controls/ListBox/ListBox.h"
#include "../../Controls/ListBox/ListBoxListItem.h"
#include "../../Controls/RadioButton/RadioButton.h"

namespace nitisa
{
	class IControl;
	class IForm;
	class IListItem;
	class IRenderer;
	class IWindow;
	struct CreateParams;

	namespace standard
	{
		class IFormBoolArrayProto : public CForm
		{
		protected:
			// Controls
			CListBox *m_pListBoxArray;
			CRadioButton *m_pRadioButtonTrue;
			CRadioButton *m_pRadioButtonFalse;
			CButton *m_pButtonAdd;
			CButton *m_pButtonUpdate;
			CButton *m_pButtonDelete;
			CButton *m_pButtonClear;
			CLabel *m_pLabel1;
			CLabel *m_pLabelMinCount;
			CButton *m_pButtonOk;
			CButton *m_pButtonCancel;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormBoolArrayProto_OnKeyUp(IForm *sender, const MessageKey &m) = 0;
			virtual void ListBoxArray_OnSelect(IControl *sender, IListItem *item) = 0;
			virtual void ButtonAdd_OnClick(IControl *sender) = 0;
			virtual void ButtonUpdate_OnClick(IControl *sender) = 0;
			virtual void ButtonDelete_OnClick(IControl *sender) = 0;
			virtual void ButtonClear_OnClick(IControl *sender) = 0;
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pListBoxArray = new CListBox(this);
				m_pListBoxArray->setName(L"ListBoxArray");
				m_pRadioButtonTrue = new CRadioButton(this);
				m_pRadioButtonTrue->setName(L"RadioButtonTrue");
				m_pRadioButtonFalse = new CRadioButton(this);
				m_pRadioButtonFalse->setName(L"RadioButtonFalse");
				m_pButtonAdd = new CButton(this);
				m_pButtonAdd->setName(L"ButtonAdd");
				m_pButtonUpdate = new CButton(this);
				m_pButtonUpdate->setName(L"ButtonUpdate");
				m_pButtonDelete = new CButton(this);
				m_pButtonDelete->setName(L"ButtonDelete");
				m_pButtonClear = new CButton(this);
				m_pButtonClear->setName(L"ButtonClear");
				m_pLabel1 = new CLabel(this);
				m_pLabel1->setName(L"Label1");
				m_pLabelMinCount = new CLabel(this);
				m_pLabelMinCount->setName(L"LabelMinCount");
				m_pButtonOk = new CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");

				// Initialize controls
				m_pListBoxArray->setName(L"ListBoxArray");
				m_pListBoxArray->getTransform()->Translate(8.0f, 8.0f, 0.0f);
				m_pListBoxArray->setSize(PointF{ 177.0f, 313.0f });
				m_pListBoxArray->setTabOrder(1);
				m_pListBoxArray->setMultiselect(false);
				m_pListBoxArray->OnSelect = [](IControl *sender, IListItem *item)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ListBoxArray_OnSelect(sender, item); };

				m_pRadioButtonTrue->setName(L"RadioButtonTrue");
				m_pRadioButtonTrue->getTransform()->Translate(192.0f, 16.0f, 0.0f);
				m_pRadioButtonTrue->setTabOrder(2);
				m_pRadioButtonTrue->setCaption(UTF8ToString("True"));
				m_pRadioButtonTrue->setChecked(true);

				m_pRadioButtonFalse->setName(L"RadioButtonFalse");
				m_pRadioButtonFalse->getTransform()->Translate(248.0f, 16.0f, 0.0f);
				m_pRadioButtonFalse->setTabOrder(3);
				m_pRadioButtonFalse->setCaption(UTF8ToString("False"));

				m_pButtonAdd->setName(L"ButtonAdd");
				m_pButtonAdd->getTransform()->Translate(192.0f, 40.0f, 0.0f);
				m_pButtonAdd->setTabOrder(4);
				m_pButtonAdd->setCaption(UTF8ToString("Add"));
				m_pButtonAdd->OnClick = [](IControl *sender)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ButtonAdd_OnClick(sender); };

				m_pButtonUpdate->setName(L"ButtonUpdate");
				m_pButtonUpdate->getTransform()->Translate(192.0f, 64.0f, 0.0f);
				m_pButtonUpdate->setTabOrder(5);
				m_pButtonUpdate->setEnabled(false);
				m_pButtonUpdate->setCaption(UTF8ToString("Update"));
				m_pButtonUpdate->OnClick = [](IControl *sender)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ButtonUpdate_OnClick(sender); };

				m_pButtonDelete->setName(L"ButtonDelete");
				m_pButtonDelete->getTransform()->Translate(192.0f, 96.0f, 0.0f);
				m_pButtonDelete->setTabOrder(6);
				m_pButtonDelete->setEnabled(false);
				m_pButtonDelete->setCaption(UTF8ToString("Delete"));
				m_pButtonDelete->OnClick = [](IControl *sender)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ButtonDelete_OnClick(sender); };

				m_pButtonClear->setName(L"ButtonClear");
				m_pButtonClear->getTransform()->Translate(192.0f, 120.0f, 0.0f);
				m_pButtonClear->setTabOrder(7);
				m_pButtonClear->setEnabled(false);
				m_pButtonClear->setCaption(UTF8ToString("Clear"));
				m_pButtonClear->OnClick = [](IControl *sender)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ButtonClear_OnClick(sender); };

				m_pLabel1->setName(L"Label1");
				m_pLabel1->getTransform()->Translate(192.0f, 304.0f, 0.0f);
				m_pLabel1->setCaption(UTF8ToString("Min count:"));

				m_pLabelMinCount->setName(L"LabelMinCount");
				m_pLabelMinCount->getTransform()->Translate(256.0f, 304.0f, 0.0f);
				m_pLabelMinCount->setCaption(UTF8ToString("0"));

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(8.0f, 328.0f, 0.0f);
				m_pButtonOk->setTabOrder(8);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(120.0f, 328.0f, 0.0f);
				m_pButtonCancel->setTabOrder(9);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { cast<IFormBoolArrayProto*>(sender->getForm())->ButtonCancel_OnClick(sender); };


			}

		public:
			IFormBoolArrayProto(IWindow *window, IRenderer *renderer, const String &class_name = L"FormBoolArrayProto", const CreateParams *params = nullptr) :
				CForm(class_name, nullptr, renderer, params),
				m_pListBoxArray{ nullptr },
				m_pRadioButtonTrue{ nullptr },
				m_pRadioButtonFalse{ nullptr },
				m_pButtonAdd{ nullptr },
				m_pButtonUpdate{ nullptr },
				m_pButtonDelete{ nullptr },
				m_pButtonClear{ nullptr },
				m_pLabel1{ nullptr },
				m_pLabelMinCount{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr }
			{
				if (window)
				{
					CLockRepaint lock(this);
					setName(L"FormBoolArrayProto");
					setCaption(UTF8ToString("Manage bool-array"));
					setClientSize(Point{ 305, 360 });
					setState(WindowState::Hidden);
					setWindowPosition(WindowPosition::MainFormCenter);
					setHasMaximizeBox(false);
					setHasMinimizeBox(false);
					setHasSizeBox(false);
					QueryService()->setWindow(window);
					Application->QueryService()->Add(this);
					Initialize();
					Repaint(Rect{ 0, 0, 0, 0 }, true);
					OnKeyUp = [](IForm *sender, const MessageKey &m)->void { cast<IFormBoolArrayProto*>(sender)->FormBoolArrayProto_OnKeyUp(sender, m); };
				}
			}
		};
	}
}
