// This file is a part of Nitisa framework
// Copyright © 2025 Nitisa. All rights reserved.
// Author: Dimitry Lysenko
// Site: http://nitisa.com
// Download: http://nitisa.com/downloads
// Documentation: http://nitisa.com/documentation
// License: http://nitisa.com/site/license

#pragma once

#include "../../../Core/ErrorInfo.h"

namespace nitisa
{
	namespace script
	{
		// General
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_CLOSE_BRACKET;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_COLON;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_COMMA;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_ELLIPSIS;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_END;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_EQUAL;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_IDENTIFIER;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_LESS;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_NAME;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_NEW_LINE;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_NUMBER;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_OPEN_BRACE;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_OPEN_BRACKET;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_OPERATOR;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_OPERATOR_NAME;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_SEMICOLON;
		extern const ErrorInfo ERROR_GENERAL_EXPECTED_STRING;
		extern const ErrorInfo ERROR_GENERAL_OPERATOR_NOT_POSTERIOR;
		extern const ErrorInfo ERROR_GENERAL_OPERATOR_NOT_PRIOR;
		extern const ErrorInfo ERROR_GENERAL_POSTERIOR_OPERATOR_NOT_ALLOWED;
		extern const ErrorInfo ERROR_GENERAL_PRIOR_OPERATOR_NOT_ALLOWED;
		extern const ErrorInfo ERROR_GENERAL_UNEXPECTED_END;
		extern const ErrorInfo ERROR_GENERAL_UNEXPECTED_OPERATOR;
		extern const ErrorInfo ERROR_GENERAL_UNEXPECTED_TOKEN;
		extern const ErrorInfo ERROR_GENERAL_UNKNOWN_IDENTIFIER;
		extern const ErrorInfo ERROR_GENERAL_UNKNOWN_TOKEN;
		// Json
		extern const ErrorInfo ERROR_JSON_EXPECTED_ARRAY_END;
		extern const ErrorInfo ERROR_JSON_EXPECTED_OBJECT_END;
		// Xml
		extern const ErrorInfo ERROR_XML_DOCTYPE_NOT_ALLOWED;
		extern const ErrorInfo ERROR_XML_ELEMENT_NOT_ALLOWED;
		extern const ErrorInfo ERROR_XML_EXPECTED_DOCTYPE;
		extern const ErrorInfo ERROR_XML_EXPECTED_ELEMENT_CLOSE_OPERATOR;
		extern const ErrorInfo ERROR_XML_PROLOG_NOT_ALLOWED;
		// Expression Builder
		extern const ErrorInfo ERROR_EB_EXPECTED_EXPRESSION_NAME;
		extern const ErrorInfo ERROR_EB_EXPECTED_NORMAL_OPERATOR;
		extern const ErrorInfo ERROR_EB_EXPECTED_OPERAND;
		extern const ErrorInfo ERROR_EB_EXPECTED_OPERATOR_BETWEEN_OPERANDS;
		extern const ErrorInfo ERROR_EB_EXPECTED_TOKENIZER;
		extern const ErrorInfo ERROR_EB_EXPECTED_TOKENS;
		extern const ErrorInfo ERROR_EB_INVALID_TOKENS_RANGE;
		extern const ErrorInfo ERROR_EB_INVALID_TOKENS_RANGE_END;
		extern const ErrorInfo ERROR_EB_INVALID_TOKENS_RANGE_START;
		extern const ErrorInfo ERROR_EB_POSTERIOR_OPERATOR_BEFORE_MEMBER_ACCESS;
		extern const ErrorInfo ERROR_EB_PRIOR_OPERATOR_AFTER_MEMBER_ACCESS;
		extern const ErrorInfo ERROR_EB_STRING_PREFIX_MISMATCH;
		extern const ErrorInfo ERROR_EB_UNEXPECTED_EXPRESSION_TYPE;
		extern const ErrorInfo ERROR_EB_UNEXPECTED_NAME_EXPRESSION_TYPE;
		extern const ErrorInfo ERROR_EB_USER_DEFINED_LITERALS_NOT_ALLOWED;
		// Expression Runner
		extern const ErrorInfo ERROR_ER_BRACE_ARGUMENTS_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_BRACE_ARGUMENTS_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_BRACE_NAME_EXPRESSION_TYPE;
		extern const ErrorInfo ERROR_ER_BRACE_NAME_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_BRACE_NAME_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_CALL_ARGUMENTS_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_CALL_ARGUMENTS_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_CALL_NAME_EXPRESSION_TYPE;
		extern const ErrorInfo ERROR_ER_CALL_NAME_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_CALL_NAME_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_CAST_DATA_TYPE_EMPTY;
		extern const ErrorInfo ERROR_ER_CAST_NAME_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_CAST_NAME_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_EMPTY_SEQUENCE;
		extern const ErrorInfo ERROR_ER_EXPECTED_BRACE_ARGUMENTS;
		extern const ErrorInfo ERROR_ER_EXPECTED_CAST_OPERAND;
		extern const ErrorInfo ERROR_ER_EXPECTED_EXPRESSION;
		extern const ErrorInfo ERROR_ER_EXPECTED_FIVE_EXPRESSIONS_FOR_TERNARY;
		extern const ErrorInfo ERROR_ER_EXPECTED_ODD_ARGUMENT_COUNT;
		extern const ErrorInfo ERROR_ER_EXPECTED_ODD_EXPRESSION_COUNT;
		extern const ErrorInfo ERROR_ER_EXPECTED_ONE_ARGUMENT;
		extern const ErrorInfo ERROR_ER_FUNCTION_NOT_FOUND;
		extern const ErrorInfo ERROR_ER_EXPECTED_OPERAND;
		extern const ErrorInfo ERROR_ER_EXPECTED_OPERATOR;
		extern const ErrorInfo ERROR_ER_EXPECTED_SUBSCRIPT_ARGUMENTS;
		extern const ErrorInfo ERROR_ER_EXPECTED_SUBSCRIPT_NAME;
		extern const ErrorInfo ERROR_ER_IDENTIFIER_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_IDENTIFIER_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_NOT_PREPARED;
		extern const ErrorInfo ERROR_ER_SUBSCRIPT_ARGUMENTS_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_SUBSCRIPT_ARGUMENTS_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_SUBSCRIPT_NAME_WITH_POSTERIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_SUBSCRIPT_NAME_WITH_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_ER_UNSUPPORTED_CAST_NAME_EXPRESSION_TYPE;
		extern const ErrorInfo ERROR_ER_UNSUPPORTED_EXPRESSION_TYPE;
		extern const ErrorInfo ERROR_ER_UNSUPPORTED_SUBSCRIPT_NAME_EXPRESSION_TYPE;
		// Functions
		extern const ErrorInfo ERROR_FUNCTION_EXPECTED_ARGUMENTS;
		extern const ErrorInfo ERROR_FUNCTION_INDEX_OUT_OF_BOUNDS;
		extern const ErrorInfo ERROR_FUNCTION_MISSING_OPERAND_1;
		extern const ErrorInfo ERROR_FUNCTION_MISSING_OPERAND_2;
		extern const ErrorInfo ERROR_FUNCTION_MISSING_OPERAND_3;
		extern const ErrorInfo ERROR_FUNCTION_OPERAND_1_NOT_ARRAY;
		extern const ErrorInfo ERROR_FUNCTION_OPERAND_1_NOT_OBJECT;
		extern const ErrorInfo ERROR_FUNCTION_OPERAND_2_NOT_IDENTIFIER;
		// C++Doc pre-rpcessor
		extern const ErrorInfo ERROR_CPPDOC_PP_DEFINITION_EXISTS;
		extern const ErrorInfo ERROR_CPPDOC_PP_DUPLICATE_VARIADIC;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_ANSI_STRING;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_DEFINE_AFTER_HASH;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_EXPRESSION;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_HASH;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_IDENTIFIER;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_IDENTIFIER_AFTER_DEFINE;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_NEW_LINE;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_ONE_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_OPERAND;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_OPERATOR;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_PARAMETER;
		extern const ErrorInfo ERROR_CPPDOC_PP_EXPECTED_TOKEN;
		extern const ErrorInfo ERROR_CPPDOC_PP_INVALID_ARGUMENT_COUNT;
		extern const ErrorInfo ERROR_CPPDOC_PP_INVALID_EXPRESSION;
		extern const ErrorInfo ERROR_CPPDOC_PP_INVALID_OPERAND;
		extern const ErrorInfo ERROR_CPPDOC_PP_INVALID_NEXT_CONCATINATE_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_PP_INVALID_PREV_CONCATINATE_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_PP_MISSING_NEXT_CONCATINATE_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_PP_MISSING_PREV_CONCATINATE_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_PP_TOO_FEW_ARGUMENTS;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNEXPECTED_END;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNEXPECTED_END_EXPECTED_EXPRESSION;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNEXPECTED_END_EXPECTED_IDENTIFIER;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNEXPECTED_END_EXPECTED_OPERAND;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNEXPECTED_PRIOR_OPERATORS;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNEXPECTED_TOKEN;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNFINISHED_BRANCH;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNKNOWN_DIRECTIVE;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNKNOWN_FUNCTION;
		extern const ErrorInfo ERROR_CPPDOC_PP_UNSUPPORTED_OPERATOR;
		// C++Doc
		extern const ErrorInfo ERROR_CPPDOC_BITFIELD_REQUIRE_ID_DECLARATOR;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_AUTO;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_FINAL;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_PRIVATE;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_PROTECTED;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_PUBLIC;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_REPLACEABLE;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_TRIVIALLY_RELOCATABLE;
		extern const ErrorInfo ERROR_CPPDOC_DUPLICATE_VIRTUAL;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_ANSI;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_AUTO;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_DECLARATOR;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_EXPRESSION;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_IDENTIFIER;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_INITIALIZATION;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_SPECIFIER;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_STRING;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_TOKEN;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_TRAILING;
		extern const ErrorInfo ERROR_CPPDOC_EXPECTED_TYPE_ID;
		extern const ErrorInfo ERROR_CPPDOC_EXPORT_MODULE_WITHOUT_NAME;
		extern const ErrorInfo ERROR_CPPDOC_EXPORT_PRIVATE_MODULE;
		extern const ErrorInfo ERROR_CPPDOC_INLINE_NOT_ALLOWED_HERE;
		extern const ErrorInfo ERROR_CPPDOC_INVALID_DECLARATOR;
		extern const ErrorInfo ERROR_CPPDOC_INVALID_IDENTIFIER;
		extern const ErrorInfo ERROR_CPPDOC_INVALID_IDENTIFIER_DOUBLE_DESTRUCTOR;
		extern const ErrorInfo ERROR_CPPDOC_INVALID_PARTITION_NAME;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_ARRAY;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_ATTRIBUTE_LIST;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_DECLARATOR;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_MEMBER_INITIALIZATION;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_MODULE_NAME;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_PARAMETERS;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_PARTITION_NAME;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_STRING;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_AFTER_TOKEN;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_EXPECTED_ARGUMENT;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_EXPECTED_ATTRIBUTE_LIST;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_EXPECTED_BASE_CLASS;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_EXPECTED_DECLARATOR;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_END_EXPECTED_IDENTIFIER;
		extern const ErrorInfo ERROR_CPPDOC_UNEXPECTED_FUNCTION_DEFINITION;
		extern const ErrorInfo ERROR_CPPDOC_UNION_WITH_BASE_CLASS;
	}
}