// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:33:10

// !!! ATTENTION !!!
// This is an auto-generated file with form declaration and initialization.
// Include it into your form class header file and derive your form from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// For example:
//     FormColorProto.h:
//         #include "IFormColorProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CFormColorProto : public IFormColorProto // Derive your form from class from this file
//                 {
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     CFormColorProto(); // Declare constructor
//                 };
//             }
//         }
//
//     FormColorProto.cpp:
//         #include "Standard/Platform/Windows/Window.h" // Include required platform window management class
//         #include "Standard/Platform/Windows/OpenGL/Renderer.h" // Include required renderer
//         #include "FormColorProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CFormColorProto::CFormColorProto(): // Implement constructor of your form
//                     IFormColorProto(new standard::windows::CWindow(), new standard::windows::opengl::CRenderer(false, 0))
//                 {
//                     // Insert your code here
//                 }
//
//                 void CFormColorProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//             }
//         }


#pragma once

#include "Nitisa/Core/Form.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/IFormService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/AlphaBar/AlphaBar.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/Edit/Edit.h"
#include "../../Controls/HSVBar/HSVBar.h"
#include "../../Controls/HSVPlane/HSVPlane.h"
#include "../../Controls/Label/Label.h"

namespace nitisa
{
	class IControl;
	class IForm;
	class IRenderer;
	class IWindow;
	struct CreateParams;

	namespace standard
	{
		class IFormColorProto : public CForm
		{
		protected:
			// Controls
			CHSVPlane *m_pHSVPlane;
			CHSVBar *m_pHSVBar;
			CAlphaBar *m_pAlphaBar;
			CLabel *m_pLabelHue;
			CEdit *m_pEditHue;
			CLabel *m_pLabelSaturation;
			CEdit *m_pEditSaturation;
			CLabel *m_pLabelValue;
			CEdit *m_pEditValue;
			CLabel *m_pLabelR;
			CEdit *m_pEditR;
			CLabel *m_pLabelG;
			CEdit *m_pEditG;
			CLabel *m_pLabelB;
			CEdit *m_pEditB;
			CLabel *m_pLabelA;
			CEdit *m_pEditA;
			CButton *m_pButtonOk;
			CButton *m_pButtonCancel;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormColorProto_OnKeyUp(IForm *sender, const MessageKey &m) = 0;
			virtual void HSVPlane_OnChange(IControl *sender) = 0;
			virtual void HSVBar_OnChange(IControl *sender) = 0;
			virtual void AlphaBar_OnChange(IControl *sender) = 0;
			virtual void EditHue_OnKillFocus(IControl *sender) = 0;
			virtual void EditHue_OnChange(IControl *sender) = 0;
			virtual void EditSaturation_OnKillFocus(IControl *sender) = 0;
			virtual void EditSaturation_OnChange(IControl *sender) = 0;
			virtual void EditValue_OnKillFocus(IControl *sender) = 0;
			virtual void EditValue_OnChange(IControl *sender) = 0;
			virtual void EditR_OnKillFocus(IControl *sender) = 0;
			virtual void EditR_OnChange(IControl *sender) = 0;
			virtual void EditG_OnKillFocus(IControl *sender) = 0;
			virtual void EditG_OnChange(IControl *sender) = 0;
			virtual void EditB_OnKillFocus(IControl *sender) = 0;
			virtual void EditB_OnChange(IControl *sender) = 0;
			virtual void EditA_OnKillFocus(IControl *sender) = 0;
			virtual void EditA_OnChange(IControl *sender) = 0;
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pHSVPlane = new CHSVPlane(this);
				m_pHSVPlane->setName(L"HSVPlane");
				m_pHSVBar = new CHSVBar(this);
				m_pHSVBar->setName(L"HSVBar");
				m_pAlphaBar = new CAlphaBar(this);
				m_pAlphaBar->setName(L"AlphaBar");
				m_pLabelHue = new CLabel(this);
				m_pLabelHue->setName(L"LabelHue");
				m_pEditHue = new CEdit(this);
				m_pEditHue->setName(L"EditHue");
				m_pLabelSaturation = new CLabel(this);
				m_pLabelSaturation->setName(L"LabelSaturation");
				m_pEditSaturation = new CEdit(this);
				m_pEditSaturation->setName(L"EditSaturation");
				m_pLabelValue = new CLabel(this);
				m_pLabelValue->setName(L"LabelValue");
				m_pEditValue = new CEdit(this);
				m_pEditValue->setName(L"EditValue");
				m_pLabelR = new CLabel(this);
				m_pLabelR->setName(L"LabelR");
				m_pEditR = new CEdit(this);
				m_pEditR->setName(L"EditR");
				m_pLabelG = new CLabel(this);
				m_pLabelG->setName(L"LabelG");
				m_pEditG = new CEdit(this);
				m_pEditG->setName(L"EditG");
				m_pLabelB = new CLabel(this);
				m_pLabelB->setName(L"LabelB");
				m_pEditB = new CEdit(this);
				m_pEditB->setName(L"EditB");
				m_pLabelA = new CLabel(this);
				m_pLabelA->setName(L"LabelA");
				m_pEditA = new CEdit(this);
				m_pEditA->setName(L"EditA");
				m_pButtonOk = new CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");

				// Initialize controls
				m_pHSVPlane->setName(L"HSVPlane");
				m_pHSVPlane->getTransform()->Translate(8.0f, 8.0f, 0.0f);
				m_pHSVPlane->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->HSVPlane_OnChange(sender); };

				m_pHSVBar->setName(L"HSVBar");
				m_pHSVBar->getTransform()->Translate(268.0f, 4.0f, 0.0f);
				m_pHSVBar->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->HSVBar_OnChange(sender); };

				m_pAlphaBar->setName(L"AlphaBar");
				m_pAlphaBar->getTransform()->Translate(312.0f, 4.0f, 0.0f);
				m_pAlphaBar->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->AlphaBar_OnChange(sender); };

				m_pLabelHue->setName(L"LabelHue");
				m_pLabelHue->getTransform()->Translate(356.0f, 12.0f, 0.0f);
				m_pLabelHue->setCaption(UTF8ToString("H:"));

				m_pEditHue->setName(L"EditHue");
				m_pEditHue->getTransform()->Translate(374.0f, 8.0f, 0.0f);
				m_pEditHue->setSize(PointF{ 50.0f, 21.0f });
				m_pEditHue->setTabOrder(5);
				m_pEditHue->setText(UTF8ToString("0"));
				m_pEditHue->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditHue_OnKillFocus(sender); };
				m_pEditHue->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditHue_OnChange(sender); };

				m_pLabelSaturation->setName(L"LabelSaturation");
				m_pLabelSaturation->getTransform()->Translate(356.0f, 36.0f, 0.0f);
				m_pLabelSaturation->setCaption(UTF8ToString("S:"));

				m_pEditSaturation->setName(L"EditSaturation");
				m_pEditSaturation->getTransform()->Translate(374.0f, 32.0f, 0.0f);
				m_pEditSaturation->setSize(PointF{ 50.0f, 21.0f });
				m_pEditSaturation->setTabOrder(7);
				m_pEditSaturation->setText(UTF8ToString("0"));
				m_pEditSaturation->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditSaturation_OnKillFocus(sender); };
				m_pEditSaturation->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditSaturation_OnChange(sender); };

				m_pLabelValue->setName(L"LabelValue");
				m_pLabelValue->getTransform()->Translate(356.0f, 60.0f, 0.0f);
				m_pLabelValue->setCaption(UTF8ToString("V:"));

				m_pEditValue->setName(L"EditValue");
				m_pEditValue->getTransform()->Translate(374.0f, 56.0f, 0.0f);
				m_pEditValue->setSize(PointF{ 50.0f, 21.0f });
				m_pEditValue->setTabOrder(9);
				m_pEditValue->setText(UTF8ToString("0"));
				m_pEditValue->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditValue_OnKillFocus(sender); };
				m_pEditValue->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditValue_OnChange(sender); };

				m_pLabelR->setName(L"LabelR");
				m_pLabelR->getTransform()->Translate(356.0f, 110.0f, 0.0f);
				m_pLabelR->setCaption(UTF8ToString("R:"));

				m_pEditR->setName(L"EditR");
				m_pEditR->getTransform()->Translate(374.0f, 106.0f, 0.0f);
				m_pEditR->setSize(PointF{ 50.0f, 21.0f });
				m_pEditR->setTabOrder(11);
				m_pEditR->setText(UTF8ToString("0"));
				m_pEditR->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditR_OnKillFocus(sender); };
				m_pEditR->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditR_OnChange(sender); };

				m_pLabelG->setName(L"LabelG");
				m_pLabelG->getTransform()->Translate(356.0f, 134.0f, 0.0f);
				m_pLabelG->setCaption(UTF8ToString("G:"));

				m_pEditG->setName(L"EditG");
				m_pEditG->getTransform()->Translate(374.0f, 130.0f, 0.0f);
				m_pEditG->setSize(PointF{ 50.0f, 21.0f });
				m_pEditG->setTabOrder(13);
				m_pEditG->setText(UTF8ToString("0"));
				m_pEditG->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditG_OnKillFocus(sender); };
				m_pEditG->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditG_OnChange(sender); };

				m_pLabelB->setName(L"LabelB");
				m_pLabelB->getTransform()->Translate(356.0f, 158.0f, 0.0f);
				m_pLabelB->setCaption(UTF8ToString("B:"));

				m_pEditB->setName(L"EditB");
				m_pEditB->getTransform()->Translate(374.0f, 154.0f, 0.0f);
				m_pEditB->setSize(PointF{ 50.0f, 21.0f });
				m_pEditB->setTabOrder(15);
				m_pEditB->setText(UTF8ToString("0"));
				m_pEditB->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditB_OnKillFocus(sender); };
				m_pEditB->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditB_OnChange(sender); };

				m_pLabelA->setName(L"LabelA");
				m_pLabelA->getTransform()->Translate(356.0f, 182.0f, 0.0f);
				m_pLabelA->setCaption(UTF8ToString("A:"));

				m_pEditA->setName(L"EditA");
				m_pEditA->getTransform()->Translate(374.0f, 178.0f, 0.0f);
				m_pEditA->setSize(PointF{ 50.0f, 21.0f });
				m_pEditA->setTabOrder(17);
				m_pEditA->setText(UTF8ToString("0"));
				m_pEditA->OnKillFocus = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditA_OnKillFocus(sender); };
				m_pEditA->OnChange = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->EditA_OnChange(sender); };

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(356.0f, 212.0f, 0.0f);
				m_pButtonOk->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonOk->setTabOrder(18);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(356.0f, 240.0f, 0.0f);
				m_pButtonCancel->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonCancel->setTabOrder(19);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { cast<IFormColorProto*>(sender->getForm())->ButtonCancel_OnClick(sender); };


			}

		public:
			IFormColorProto(IWindow *window, IRenderer *renderer, const String &class_name = L"FormColorProto", const CreateParams *params = nullptr) :
				CForm(class_name, nullptr, renderer, params),
				m_pHSVPlane{ nullptr },
				m_pHSVBar{ nullptr },
				m_pAlphaBar{ nullptr },
				m_pLabelHue{ nullptr },
				m_pEditHue{ nullptr },
				m_pLabelSaturation{ nullptr },
				m_pEditSaturation{ nullptr },
				m_pLabelValue{ nullptr },
				m_pEditValue{ nullptr },
				m_pLabelR{ nullptr },
				m_pEditR{ nullptr },
				m_pLabelG{ nullptr },
				m_pEditG{ nullptr },
				m_pLabelB{ nullptr },
				m_pEditB{ nullptr },
				m_pLabelA{ nullptr },
				m_pEditA{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr }
			{
				if (window)
				{
					CLockRepaint lock(this);
					setName(L"FormColorProto");
					setCaption(UTF8ToString("Select Color"));
					setClientSize(Point{ 432, 272 });
					setState(WindowState::Hidden);
					setWindowPosition(WindowPosition::MainFormCenter);
					setHasMaximizeBox(false);
					setHasMinimizeBox(false);
					setHasSizeBox(false);
					QueryService()->setWindow(window);
					Application->QueryService()->Add(this);
					Initialize();
					Repaint(Rect{ 0, 0, 0, 0 }, true);
					OnKeyUp = [](IForm *sender, const MessageKey &m)->void { cast<IFormColorProto*>(sender)->FormColorProto_OnKeyUp(sender, m); };
				}
			}
		};
	}
}
