// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:32:05

// !!! ATTENTION !!!
// This is an auto-generated file with dialog box widget prototype declaration and initialization.
// Include it into your dialog box widget class header file and derive your widget from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// Also add service(if your widget need one) derived from service prototype below(do not forget to call parent class methods wher overwriting methods).
// For example:
//     DialogBoxRectDProto.h:
//         #include "Nitisa/Core/Consts.h" // DesignDPI constant is declared here
//         #include "Nitisa/Image/Color.h" // Color declaration is here
//         #include "IDialogBoxRectDProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CDialogBoxRectDProto : public IDialogBoxRectDProto // Derive your widget from class from this file
//                 {
//                 private: // Private members for handling widget logic
//                     Color m_sBackgroundColor; // Store background color
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     // IDialogBox's abstract methods re-declaration
//                     Color getBackgroundColor() override;
//                     // Add other abstract methods needed to be implemented
//
//                     CDialogBoxRectDProto(); // Declare constructor
//                 };
//             }
//         }
//
//     DialogBoxRectDProto.cpp:
//         #include "DialogBoxRectDProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CDialogBoxRectDProto::CDialogBoxRectDProto(): // Implement constructor of your widget
//                     IDialogBoxRectDProto(L"DialogBoxRectDProto", true, true, false, false, DesignDPI) // Here you may add your service implementation as the latest parameter
//                 {
//                     // Insert your code here
//                 }
//
//                 void CDialogBoxRectDProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//
//                 Color CDialogBoxRectDProto::getBackgroundColor() // Implement IDialogBox's getBackgroundColor() methods
//                 {
//                     return m_sBackgroundColor;
//                 }
//                 // Implement other IDialogBox's abstract methods
//             }
//         }

#pragma once

#include "Nitisa/Core/Consts.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/DialogBoxEx/DialogBoxEx.h"
#include "../../Controls/DialogBoxEx/DialogBoxExService.h"
#include "../../Controls/Edit/Edit.h"

namespace nitisa
{
	class IControl;
	class IDialogBoxService;
	class IForm;

	namespace standard
	{
		class IDialogBoxRectDProto : public CDialogBoxEx
		{
		public:
			class IDialogBoxRectDProtoService: public CDialogBoxExService
			{
			private:
				IDialogBoxRectDProto *m_pControl;
			public:
				void NotifyOnAttach() override
				{
					CDialogBoxExService::NotifyOnAttach();
					if (m_pControl->getForm())
					{
					}
				}

				void NotifyOnDetaching() override
				{
					CDialogBoxExService::NotifyOnDetaching();
				}

				IDialogBoxRectDProtoService(IDialogBoxRectDProto *control) : CDialogBoxExService(control),
					m_pControl{ control }
				{

				}
			};
		protected:
			// Controls
			CEdit *m_pEditLeft;
			CEdit *m_pEditTop;
			CEdit *m_pEditRight;
			CEdit *m_pEditBottom;
			CButton *m_pButtonOk;
			CButton *m_pButtonCancel;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormRectDProto_OnPaint(IControl *sender, const MessagePaint &m, bool &draw_children) = 0;
			virtual void FormRectDProto_OnKeyUp(IControl *sender, const MessageKey &m, bool &processed) = 0;
			virtual void EditLeft_OnKillFocus(IControl *sender) = 0;
			virtual void EditTop_OnKillFocus(IControl *sender) = 0;
			virtual void EditRight_OnKillFocus(IControl *sender) = 0;
			virtual void EditBottom_OnKillFocus(IControl *sender) = 0;
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pEditLeft = new CEdit(this);
				m_pEditLeft->setName(L"EditLeft");
				m_pEditTop = new CEdit(this);
				m_pEditTop->setName(L"EditTop");
				m_pEditRight = new CEdit(this);
				m_pEditRight->setName(L"EditRight");
				m_pEditBottom = new CEdit(this);
				m_pEditBottom->setName(L"EditBottom");
				m_pButtonOk = new CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");

				// Initialize controls
				m_pEditLeft->setName(L"EditLeft");
				m_pEditLeft->getTransform()->Translate(11.0f, 38.0f, 0.0f);
				m_pEditLeft->setSize(PointF{ 100.0f, 21.0f });
				m_pEditLeft->setTabOrder(1);
				m_pEditLeft->setText(UTF8ToString("0"));
				m_pEditLeft->OnKillFocus = [](IControl *sender)->void { parent<IDialogBoxRectDProto*, false>(sender)->EditLeft_OnKillFocus(sender); };

				m_pEditTop->setName(L"EditTop");
				m_pEditTop->getTransform()->Translate(83.0f, 11.0f, 0.0f);
				m_pEditTop->setSize(PointF{ 100.0f, 21.0f });
				m_pEditTop->setTabOrder(2);
				m_pEditTop->setText(UTF8ToString("0"));
				m_pEditTop->OnKillFocus = [](IControl *sender)->void { parent<IDialogBoxRectDProto*, false>(sender)->EditTop_OnKillFocus(sender); };

				m_pEditRight->setName(L"EditRight");
				m_pEditRight->getTransform()->Translate(155.0f, 38.0f, 0.0f);
				m_pEditRight->setSize(PointF{ 100.0f, 21.0f });
				m_pEditRight->setTabOrder(3);
				m_pEditRight->setText(UTF8ToString("0"));
				m_pEditRight->OnKillFocus = [](IControl *sender)->void { parent<IDialogBoxRectDProto*, false>(sender)->EditRight_OnKillFocus(sender); };

				m_pEditBottom->setName(L"EditBottom");
				m_pEditBottom->getTransform()->Translate(83.0f, 65.0f, 0.0f);
				m_pEditBottom->setSize(PointF{ 100.0f, 21.0f });
				m_pEditBottom->setTabOrder(4);
				m_pEditBottom->setText(UTF8ToString("0"));
				m_pEditBottom->OnKillFocus = [](IControl *sender)->void { parent<IDialogBoxRectDProto*, false>(sender)->EditBottom_OnKillFocus(sender); };

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(63.0f, 92.0f, 0.0f);
				m_pButtonOk->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonOk->setTabOrder(5);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { parent<IDialogBoxRectDProto*, false>(sender)->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(135.0f, 92.0f, 0.0f);
				m_pButtonCancel->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonCancel->setTabOrder(6);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { parent<IDialogBoxRectDProto*, false>(sender)->ButtonCancel_OnClick(sender); };


			}

		public:
			IDialogBoxRectDProto(const String &class_name, const bool accept_form, const bool accept_control, const bool accept_focus, const bool tab_stop, const Point &design_dpi = DesignDPI, IDialogBoxService *service = nullptr) :
				CDialogBoxEx(class_name, accept_form, accept_control, accept_focus, tab_stop, design_dpi, service ? service : new IDialogBoxRectDProtoService(this)),
				m_pEditLeft{ nullptr },
				m_pEditTop{ nullptr },
				m_pEditRight{ nullptr },
				m_pEditBottom{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr }
			{
				CLockRepaint lock(this);
				setName(L"DialogBoxRectDProto");
				setCaption(UTF8ToString("Borders(double)"));
				setClientSize(Point{ 266, 123 });
				setWindowPosition(WindowPosition::MainFormCenter);
				setState(WindowState::Hidden);
				setHasMaximizeBox(false);
				setHasMinimizeBox(false);
				setHasSizeBox(false);
				Initialize();
				OnPaint = [](IControl *sender, const MessagePaint &m, bool &draw_children)->void { cast<IDialogBoxRectDProto*>(sender)->FormRectDProto_OnPaint(sender, m, draw_children); };
				OnKeyUp = [](IControl *sender, const MessageKey &m, bool &processed)->void { cast<IDialogBoxRectDProto*>(sender)->FormRectDProto_OnKeyUp(sender, m, processed); };
			}

			IComponent *getComponent(const String &name)
			{
				return nullptr;
			}

			IControl *FindControl(const String &name, IControl *exclude = nullptr) override
			{
				if (name == L"EditLeft" && m_pEditLeft != exclude)
					return m_pEditLeft;
				if (name == L"EditTop" && m_pEditTop != exclude)
					return m_pEditTop;
				if (name == L"EditRight" && m_pEditRight != exclude)
					return m_pEditRight;
				if (name == L"EditBottom" && m_pEditBottom != exclude)
					return m_pEditBottom;
				if (name == L"ButtonOk" && m_pButtonOk != exclude)
					return m_pButtonOk;
				if (name == L"ButtonCancel" && m_pButtonCancel != exclude)
					return m_pButtonCancel;
				return nullptr;
			}

		};
	}
}

