// This file is a part of Nitisa framework
// Copyright © 2020 Nitisa. All rights reserved.
// Author: Dimitry Lysenko
// Site: http://nitisa.com
// Download: http://nitisa.com/downloads
// Documentation: http://nitisa.com/documentation
// License: http://nitisa.com/site/license

#pragma once

// Controls
#include "Controls/3DObject/3DObject.h"
#include "Controls/BlinnPhongMaterial/BlinnPhongMaterial.h"
#include "Controls/BlinnPhongMaterial/BlinnPhongMaterialService.h"
#include "Controls/Box/Box.h"
#include "Controls/CheckerMaterial/CheckerMaterial.h"
#include "Controls/CheckerMaterial/CheckerMaterialService.h"
#include "Controls/Circle/Circle.h"
#include "Controls/Cone/Cone.h"
#include "Controls/CustomMaterial/CustomMaterial.h"
#include "Controls/CustomMaterial/CustomMaterialService.h"
#include "Controls/Cylinder/Cylinder.h"
#include "Controls/Disk/Disk.h"
#include "Controls/GouraudMaterial/GouraudMaterial.h"
#include "Controls/GouraudMaterial/GouraudMaterialService.h"
#include "Controls/Heightmap/Heightmap.h"
#include "Controls/JsonMesh/JsonMesh.h"
#include "Controls/Mesh/Mesh.h"
#include "Controls/PhongMaterial/PhongMaterial.h"
#include "Controls/PhongMaterial/PhongMaterialService.h"
#include "Controls/Plane/Plane.h"
#include "Controls/Pyramid/Pyramid.h"
#include "Controls/RimMaterial/RimMaterial.h"
#include "Controls/RimMaterial/RimMaterialService.h"
#include "Controls/SolidMaterial/SolidMaterial.h"
#include "Controls/SolidMaterial/SolidMaterialService.h"
#include "Controls/Sphere/Sphere.h"
#include "Controls/Torus/Torus.h"
#include "Controls/Tube/Tube.h"
#include "Controls/View/View.h"
#include "Controls/View/ViewService.h"
#include "Controls/I3DObject.h"
#include "Controls/IBlinnPhongMaterial.h"
#include "Controls/IBox.h"
#include "Controls/ICheckerMaterial.h"
#include "Controls/ICircle.h"
#include "Controls/ICone.h"
#include "Controls/ICustomMaterial.h"
#include "Controls/ICylinder.h"
#include "Controls/IDisk.h"
#include "Controls/IGouraudMaterial.h"
#include "Controls/IHeightmap.h"
#include "Controls/IJsonMesh.h"
#include "Controls/IMesh.h"
#include "Controls/IPhongMaterial.h"
#include "Controls/IPlane.h"
#include "Controls/IPyramid.h"
#include "Controls/IRimMaterial.h"
#include "Controls/ISolidMaterial.h"
#include "Controls/ISphere.h"
#include "Controls/ITorus.h"
#include "Controls/ITube.h"
#include "Controls/IView.h"

// Core
#include "Core/3DControl.h"
#include "Core/3DControlService.h"
#include "Core/Consts.h"

// Interfaces
#include "Interfaces/I3DControl.h"
#include "Interfaces/I3DControlService.h"
#include "Interfaces/IMaterialControl.h"

// Package controls
#include "Package/Controls/3DObject/3DObjectEventList.h"
#include "Package/Controls/3DObject/3DObjectPropertyList.h"
#include "Package/Controls/3DObject/Package3DObject.h"
#include "Package/Controls/BlinnPhongMaterial/BlinnPhongMaterialEventList.h"
#include "Package/Controls/BlinnPhongMaterial/BlinnPhongMaterialPropertyList.h"
#include "Package/Controls/BlinnPhongMaterial/PackageBlinnPhongMaterial.h"
#include "Package/Controls/Box/BoxEventList.h"
#include "Package/Controls/Box/BoxPropertyList.h"
#include "Package/Controls/Box/PackageBox.h"
#include "Package/Controls/CheckerMaterial/CheckerMaterialEventList.h"
#include "Package/Controls/CheckerMaterial/CheckerMaterialPropertyList.h"
#include "Package/Controls/CheckerMaterial/PackageCheckerMaterial.h"
#include "Package/Controls/Circle/CircleEventList.h"
#include "Package/Controls/Circle/CirclePropertyList.h"
#include "Package/Controls/Circle/PackageCircle.h"
#include "Package/Controls/Cone/ConeEventList.h"
#include "Package/Controls/Cone/ConePropertyList.h"
#include "Package/Controls/Cone/PackageCone.h"
#include "Package/Controls/CustomMaterial/CustomMaterialEventList.h"
#include "Package/Controls/CustomMaterial/CustomMaterialPropertyList.h"
#include "Package/Controls/CustomMaterial/PackageCustomMaterial.h"
#include "Package/Controls/Cylinder/CylinderEventList.h"
#include "Package/Controls/Cylinder/CylinderPropertyList.h"
#include "Package/Controls/Cylinder/PackageCylinder.h"
#include "Package/Controls/Disk/DiskEventList.h"
#include "Package/Controls/Disk/DiskPropertyList.h"
#include "Package/Controls/Disk/PackageDisk.h"
#include "Package/Controls/GouraudMaterial/GouraudMaterialEventList.h"
#include "Package/Controls/GouraudMaterial/GouraudMaterialPropertyList.h"
#include "Package/Controls/GouraudMaterial/PackageGouraudMaterial.h"
#include "Package/Controls/Heightmap/HeightmapEventList.h"
#include "Package/Controls/Heightmap/HeightmapPropertyList.h"
#include "Package/Controls/Heightmap/PackageHeightmap.h"
#include "Package/Controls/JsonMesh/JsonMeshEventList.h"
#include "Package/Controls/JsonMesh/JsonMeshPropertyList.h"
#include "Package/Controls/JsonMesh/PackageJsonMesh.h"
#include "Package/Controls/Mesh/MeshEventList.h"
#include "Package/Controls/Mesh/MeshPropertyList.h"
#include "Package/Controls/Mesh/PackageMesh.h"
#include "Package/Controls/PhongMaterial/PhongMaterialEventList.h"
#include "Package/Controls/PhongMaterial/PhongMaterialPropertyList.h"
#include "Package/Controls/PhongMaterial/PackagePhongMaterial.h"
#include "Package/Controls/Plane/PlaneEventList.h"
#include "Package/Controls/Plane/PlanePropertyList.h"
#include "Package/Controls/Plane/PackagePlane.h"
#include "Package/Controls/Pyramid/PyramidEventList.h"
#include "Package/Controls/Pyramid/PyramidPropertyList.h"
#include "Package/Controls/Pyramid/PackagePyramid.h"
#include "Package/Controls/RimMaterial/RimMaterialEventList.h"
#include "Package/Controls/RimMaterial/RimMaterialPropertyList.h"
#include "Package/Controls/RimMaterial/PackageRimMaterial.h"
#include "Package/Controls/SolidMaterial/SolidMaterialEventList.h"
#include "Package/Controls/SolidMaterial/SolidMaterialPropertyList.h"
#include "Package/Controls/SolidMaterial/PackageSolidMaterial.h"
#include "Package/Controls/Sphere/SphereEventList.h"
#include "Package/Controls/Sphere/SpherePropertyList.h"
#include "Package/Controls/Sphere/PackageSphere.h"
#include "Package/Controls/Torus/TorusEventList.h"
#include "Package/Controls/Torus/TorusPropertyList.h"
#include "Package/Controls/Torus/PackageTorus.h"
#include "Package/Controls/Tube/TubeEventList.h"
#include "Package/Controls/Tube/TubePropertyList.h"
#include "Package/Controls/Tube/PackageTube.h"
#include "Package/Controls/View/ViewEventList.h"
#include "Package/Controls/View/ViewPropertyList.h"
#include "Package/Controls/View/PackageView.h"

// Package core
#include "Package/Core/3DControlEventList.h"
#include "Package/Core/3DControlPropertyList.h"
#include "Package/Core/Consts.h"
#include "Package/Core/MaterialControlEventList.h"
#include "Package/Core/MaterialControlPropertyList.h"
#include "Package/Core/Package3DControl.h"
#include "Package/Core/PackageMaterialControl.h"

// Package interfaces
#include "Package/Interfaces/IPropertyControlMaterial.h"
#include "Package/Interfaces/IPropertyControlMaterialState.h"

// Package properties
#include "Package/Properties/PropertyControlMaterial.h"
#include "Package/Properties/PropertyControlMaterialState.h"

// Package property handlers
#include "Package/PropertyHandlers/ControlMaterial/PropertyHandlerControlMaterial.h"

// Package
#include "Package/PackageOpenGL.h"
#include "Package/PackageOpenGLService.h"

// Primitives
#include "Primitives/2D/Circle/PrimitiveCircle.h"
#include "Primitives/2D/Disk/PrimitiveDisk.h"
#include "Primitives/2D/Plane/PrimitivePlane.h"
#include "Primitives/3D/Box/PrimitiveBox.h"
#include "Primitives/3D/Cone/PrimitiveCone.h"
#include "Primitives/3D/Cylinder/PrimitiveCylinder.h"
#include "Primitives/3D/Pyramid/PrimitivePyramid.h"
#include "Primitives/3D/Sphere/PrimitiveSphere.h"
#include "Primitives/3D/Torus/PrimitiveTorus.h"
#include "Primitives/3D/Tube/PrimitiveTube.h"

// Shaders
#include "Shaders/BlinnPhong.h"
#include "Shaders/Checker.h"
#include "Shaders/Gouraud.h"
#include "Shaders/Phong.h"
#include "Shaders/Rim.h"
#include "Shaders/Solid.h"