// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 11:28:47

// !!! ATTENTION !!!
// This is an auto-generated file with form declaration and initialization.
// Include it into your form class header file and derive your form from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// For example:
//     FormForexChartDataProto.h:
//         #include "IFormForexChartDataProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace charts
//             {
//                 class CFormForexChartDataProto : public IFormForexChartDataProto // Derive your form from class from this file
//                 {
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     CFormForexChartDataProto(); // Declare constructor
//                 };
//             }
//         }
//
//     FormForexChartDataProto.cpp:
//         #include "Standard/Platform/Windows/Window.h" // Include required platform window management class
//         #include "Standard/Platform/Windows/OpenGL/Renderer.h" // Include required renderer
//         #include "FormForexChartDataProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace charts
//             {
//                 CFormForexChartDataProto::CFormForexChartDataProto(): // Implement constructor of your form
//                     IFormForexChartDataProto(new standard::windows::CWindow(), new standard::windows::opengl::CRenderer(false, 0))
//                 {
//                     // Insert your code here
//                 }
//
//                 void CFormForexChartDataProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//             }
//         }


#pragma once

#include "Nitisa/Core/Form.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/IFormService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "Standard/Controls/Button/Button.h"
#include "Standard/Controls/DatePicker/DatePicker.h"
#include "Standard/Controls/Edit/Edit.h"
#include "Standard/Controls/Label/Label.h"
#include "Standard/Controls/ListBox/CustomListBox.h"
#include "Standard/Controls/ListBox/ListBox.h"
#include "Standard/Controls/ListBox/ListBoxListItem.h"
#include "Standard/Controls/TimePicker/TimePicker.h"

namespace nitisa
{
	class IControl;
	class IForm;
	class IListItem;
	class IRenderer;
	class IWindow;
	struct CreateParams;

	namespace charts
	{
		class IFormForexChartDataProto : public CForm
		{
		protected:
			// Controls
			standard::CListBox *m_pListBoxArray;
			standard::CButton *m_pButtonAdd;
			standard::CButton *m_pButtonUpdate;
			standard::CButton *m_pButtonDelete;
			standard::CButton *m_pButtonClear;
			standard::CButton *m_pButtonOk;
			standard::CButton *m_pButtonCancel;
			standard::CLabel *m_pLabel1;
			standard::CLabel *m_pLabel2;
			standard::CLabel *m_pLabel3;
			standard::CLabel *m_pLabel4;
			standard::CEdit *m_pEditOpen;
			standard::CEdit *m_pEditClose;
			standard::CEdit *m_pEditMin;
			standard::CEdit *m_pEditMax;
			standard::CLabel *m_pLabel5;
			standard::CDatePicker *m_pDatePicker;
			standard::CTimePicker *m_pTimePicker;
			standard::CLabel *m_pLabel6;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormForexChartDataProto_OnKeyUp(IForm *sender, const MessageKey &m) = 0;
			virtual void ListBoxArray_OnSelect(IControl *sender, IListItem *item) = 0;
			virtual void ButtonAdd_OnClick(IControl *sender) = 0;
			virtual void ButtonUpdate_OnClick(IControl *sender) = 0;
			virtual void ButtonDelete_OnClick(IControl *sender) = 0;
			virtual void ButtonClear_OnClick(IControl *sender) = 0;
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pListBoxArray = new standard::CListBox(this);
				m_pListBoxArray->setName(L"ListBoxArray");
				m_pButtonAdd = new standard::CButton(this);
				m_pButtonAdd->setName(L"ButtonAdd");
				m_pButtonUpdate = new standard::CButton(this);
				m_pButtonUpdate->setName(L"ButtonUpdate");
				m_pButtonDelete = new standard::CButton(this);
				m_pButtonDelete->setName(L"ButtonDelete");
				m_pButtonClear = new standard::CButton(this);
				m_pButtonClear->setName(L"ButtonClear");
				m_pButtonOk = new standard::CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new standard::CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");
				m_pLabel1 = new standard::CLabel(this);
				m_pLabel1->setName(L"Label1");
				m_pLabel2 = new standard::CLabel(this);
				m_pLabel2->setName(L"Label2");
				m_pLabel3 = new standard::CLabel(this);
				m_pLabel3->setName(L"Label3");
				m_pLabel4 = new standard::CLabel(this);
				m_pLabel4->setName(L"Label4");
				m_pEditOpen = new standard::CEdit(this);
				m_pEditOpen->setName(L"EditOpen");
				m_pEditClose = new standard::CEdit(this);
				m_pEditClose->setName(L"EditClose");
				m_pEditMin = new standard::CEdit(this);
				m_pEditMin->setName(L"EditMin");
				m_pEditMax = new standard::CEdit(this);
				m_pEditMax->setName(L"EditMax");
				m_pLabel5 = new standard::CLabel(this);
				m_pLabel5->setName(L"Label5");
				m_pDatePicker = new standard::CDatePicker(this);
				m_pDatePicker->setName(L"DatePicker");
				m_pTimePicker = new standard::CTimePicker(this);
				m_pTimePicker->setName(L"TimePicker");
				m_pLabel6 = new standard::CLabel(this);
				m_pLabel6->setName(L"Label6");

				// Initialize controls
				m_pListBoxArray->setName(L"ListBoxArray");
				m_pListBoxArray->getTransform()->Translate(8.0f, 8.0f, 0.0f);
				m_pListBoxArray->setSize(PointF{ 481.0f, 313.0f });
				m_pListBoxArray->setTabOrder(1);
				m_pListBoxArray->setMultiselect(false);
				m_pListBoxArray->OnSelect = [](IControl *sender, IListItem *item)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ListBoxArray_OnSelect(sender, item); };

				m_pButtonAdd->setName(L"ButtonAdd");
				m_pButtonAdd->getTransform()->Translate(536.0f, 160.0f, 0.0f);
				m_pButtonAdd->setTabOrder(4);
				m_pButtonAdd->setCaption(UTF8ToString("Add"));
				m_pButtonAdd->OnClick = [](IControl *sender)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ButtonAdd_OnClick(sender); };

				m_pButtonUpdate->setName(L"ButtonUpdate");
				m_pButtonUpdate->getTransform()->Translate(536.0f, 184.0f, 0.0f);
				m_pButtonUpdate->setTabOrder(5);
				m_pButtonUpdate->setEnabled(false);
				m_pButtonUpdate->setCaption(UTF8ToString("Update"));
				m_pButtonUpdate->OnClick = [](IControl *sender)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ButtonUpdate_OnClick(sender); };

				m_pButtonDelete->setName(L"ButtonDelete");
				m_pButtonDelete->getTransform()->Translate(536.0f, 216.0f, 0.0f);
				m_pButtonDelete->setTabOrder(6);
				m_pButtonDelete->setEnabled(false);
				m_pButtonDelete->setCaption(UTF8ToString("Delete"));
				m_pButtonDelete->OnClick = [](IControl *sender)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ButtonDelete_OnClick(sender); };

				m_pButtonClear->setName(L"ButtonClear");
				m_pButtonClear->getTransform()->Translate(536.0f, 240.0f, 0.0f);
				m_pButtonClear->setTabOrder(7);
				m_pButtonClear->setEnabled(false);
				m_pButtonClear->setCaption(UTF8ToString("Clear"));
				m_pButtonClear->OnClick = [](IControl *sender)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ButtonClear_OnClick(sender); };

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(8.0f, 328.0f, 0.0f);
				m_pButtonOk->setTabOrder(8);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(120.0f, 328.0f, 0.0f);
				m_pButtonCancel->setTabOrder(9);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { cast<IFormForexChartDataProto*>(sender->getForm())->ButtonCancel_OnClick(sender); };

				m_pLabel1->setName(L"Label1");
				m_pLabel1->getTransform()->Translate(496.0f, 60.0f, 0.0f);
				m_pLabel1->setCaption(UTF8ToString("Open:"));

				m_pLabel2->setName(L"Label2");
				m_pLabel2->getTransform()->Translate(496.0f, 84.0f, 0.0f);
				m_pLabel2->setCaption(UTF8ToString("Close:"));

				m_pLabel3->setName(L"Label3");
				m_pLabel3->getTransform()->Translate(496.0f, 108.0f, 0.0f);
				m_pLabel3->setCaption(UTF8ToString("Min:"));

				m_pLabel4->setName(L"Label4");
				m_pLabel4->getTransform()->Translate(496.0f, 132.0f, 0.0f);
				m_pLabel4->setCaption(UTF8ToString("Max:"));

				m_pEditOpen->setName(L"EditOpen");
				m_pEditOpen->getTransform()->Translate(536.0f, 56.0f, 0.0f);
				m_pEditOpen->setSize(PointF{ 104.0f, 21.0f });
				m_pEditOpen->setTabOrder(12);
				m_pEditOpen->setText(UTF8ToString("0.000000"));

				m_pEditClose->setName(L"EditClose");
				m_pEditClose->getTransform()->Translate(536.0f, 80.0f, 0.0f);
				m_pEditClose->setSize(PointF{ 104.0f, 21.0f });
				m_pEditClose->setTabOrder(13);
				m_pEditClose->setText(UTF8ToString("0.000000"));

				m_pEditMin->setName(L"EditMin");
				m_pEditMin->getTransform()->Translate(536.0f, 104.0f, 0.0f);
				m_pEditMin->setSize(PointF{ 104.0f, 21.0f });
				m_pEditMin->setTabOrder(14);
				m_pEditMin->setText(UTF8ToString("0.000000"));

				m_pEditMax->setName(L"EditMax");
				m_pEditMax->getTransform()->Translate(536.0f, 128.0f, 0.0f);
				m_pEditMax->setSize(PointF{ 104.0f, 21.0f });
				m_pEditMax->setTabOrder(15);
				m_pEditMax->setText(UTF8ToString("0.000000"));

				m_pLabel5->setName(L"Label5");
				m_pLabel5->getTransform()->Translate(496.0f, 12.0f, 0.0f);
				m_pLabel5->setCaption(UTF8ToString("Date:"));

				m_pDatePicker->setName(L"DatePicker");
				m_pDatePicker->getTransform()->Translate(536.0f, 8.0f, 0.0f);
				m_pDatePicker->setSize(PointF{ 104.0f, 21.0f });
				m_pDatePicker->setTabOrder(17);
				m_pDatePicker->setDisplayMode(standard::CDatePicker::DisplayMode::UpDown);
				m_pDatePicker->setElementOrder(standard::CDatePicker::ElementOrder::YearMonthDay);
				m_pDatePicker->setSeparator1(UTF8ToString("-"));
				m_pDatePicker->setSeparator2(UTF8ToString("-"));

				m_pTimePicker->setName(L"TimePicker");
				m_pTimePicker->getTransform()->Translate(536.0f, 32.0f, 0.0f);
				m_pTimePicker->setSize(PointF{ 104.0f, 21.0f });
				m_pTimePicker->setTabOrder(18);

				m_pLabel6->setName(L"Label6");
				m_pLabel6->getTransform()->Translate(496.0f, 36.0f, 0.0f);
				m_pLabel6->setCaption(UTF8ToString("Time:"));


			}

		public:
			IFormForexChartDataProto(IWindow *window, IRenderer *renderer, const String &class_name = L"FormForexChartDataProto", const CreateParams *params = nullptr) :
				CForm(class_name, nullptr, renderer, params),
				m_pListBoxArray{ nullptr },
				m_pButtonAdd{ nullptr },
				m_pButtonUpdate{ nullptr },
				m_pButtonDelete{ nullptr },
				m_pButtonClear{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr },
				m_pLabel1{ nullptr },
				m_pLabel2{ nullptr },
				m_pLabel3{ nullptr },
				m_pLabel4{ nullptr },
				m_pEditOpen{ nullptr },
				m_pEditClose{ nullptr },
				m_pEditMin{ nullptr },
				m_pEditMax{ nullptr },
				m_pLabel5{ nullptr },
				m_pDatePicker{ nullptr },
				m_pTimePicker{ nullptr },
				m_pLabel6{ nullptr }
			{
				if (window)
				{
					CLockRepaint lock(this);
					setName(L"FormForexChartDataProto");
					setCaption(UTF8ToString("Manage Forex Data"));
					setClientSize(Point{ 648, 360 });
					setState(WindowState::Hidden);
					setWindowPosition(WindowPosition::MainFormCenter);
					setHasMaximizeBox(false);
					setHasMinimizeBox(false);
					setHasSizeBox(false);
					QueryService()->setWindow(window);
					Application->QueryService()->Add(this);
					Initialize();
					Repaint(Rect{ 0, 0, 0, 0 }, true);
					OnKeyUp = [](IForm *sender, const MessageKey &m)->void { cast<IFormForexChartDataProto*>(sender)->FormForexChartDataProto_OnKeyUp(sender, m); };
				}
			}
		};
	}
}
