// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:31:56

// !!! ATTENTION !!!
// This is an auto-generated file with dialog box widget prototype declaration and initialization.
// Include it into your dialog box widget class header file and derive your widget from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// Also add service(if your widget need one) derived from service prototype below(do not forget to call parent class methods wher overwriting methods).
// For example:
//     DialogBoxRectBProto.h:
//         #include "Nitisa/Core/Consts.h" // DesignDPI constant is declared here
//         #include "Nitisa/Image/Color.h" // Color declaration is here
//         #include "IDialogBoxRectBProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CDialogBoxRectBProto : public IDialogBoxRectBProto // Derive your widget from class from this file
//                 {
//                 private: // Private members for handling widget logic
//                     Color m_sBackgroundColor; // Store background color
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     // IDialogBox's abstract methods re-declaration
//                     Color getBackgroundColor() override;
//                     // Add other abstract methods needed to be implemented
//
//                     CDialogBoxRectBProto(); // Declare constructor
//                 };
//             }
//         }
//
//     DialogBoxRectBProto.cpp:
//         #include "DialogBoxRectBProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CDialogBoxRectBProto::CDialogBoxRectBProto(): // Implement constructor of your widget
//                     IDialogBoxRectBProto(L"DialogBoxRectBProto", true, true, false, false, DesignDPI) // Here you may add your service implementation as the latest parameter
//                 {
//                     // Insert your code here
//                 }
//
//                 void CDialogBoxRectBProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//
//                 Color CDialogBoxRectBProto::getBackgroundColor() // Implement IDialogBox's getBackgroundColor() methods
//                 {
//                     return m_sBackgroundColor;
//                 }
//                 // Implement other IDialogBox's abstract methods
//             }
//         }

#pragma once

#include "Nitisa/Core/Consts.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/CheckBox/CheckBox.h"
#include "../../Controls/DialogBoxEx/DialogBoxEx.h"
#include "../../Controls/DialogBoxEx/DialogBoxExService.h"

namespace nitisa
{
	class IControl;
	class IDialogBoxService;
	class IForm;

	namespace standard
	{
		class IDialogBoxRectBProto : public CDialogBoxEx
		{
		public:
			class IDialogBoxRectBProtoService: public CDialogBoxExService
			{
			private:
				IDialogBoxRectBProto *m_pControl;
			public:
				void NotifyOnAttach() override
				{
					CDialogBoxExService::NotifyOnAttach();
					if (m_pControl->getForm())
					{
					}
				}

				void NotifyOnDetaching() override
				{
					CDialogBoxExService::NotifyOnDetaching();
				}

				IDialogBoxRectBProtoService(IDialogBoxRectBProto *control) : CDialogBoxExService(control),
					m_pControl{ control }
				{

				}
			};
		protected:
			// Controls
			CCheckBox *m_pCheckBoxLeft;
			CCheckBox *m_pCheckBoxTop;
			CCheckBox *m_pCheckBoxRight;
			CCheckBox *m_pCheckBoxBottom;
			CButton *m_pButtonOk;
			CButton *m_pButtonCancel;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormRectBProto_OnPaint(IControl *sender, const MessagePaint &m, bool &draw_children) = 0;
			virtual void FormRectBProto_OnKeyUp(IControl *sender, const MessageKey &m, bool &processed) = 0;
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pCheckBoxLeft = new CCheckBox(this);
				m_pCheckBoxLeft->setName(L"CheckBoxLeft");
				m_pCheckBoxTop = new CCheckBox(this);
				m_pCheckBoxTop->setName(L"CheckBoxTop");
				m_pCheckBoxRight = new CCheckBox(this);
				m_pCheckBoxRight->setName(L"CheckBoxRight");
				m_pCheckBoxBottom = new CCheckBox(this);
				m_pCheckBoxBottom->setName(L"CheckBoxBottom");
				m_pButtonOk = new CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");

				// Initialize controls
				m_pCheckBoxLeft->setName(L"CheckBoxLeft");
				m_pCheckBoxLeft->getTransform()->Translate(11.0f, 43.0f, 0.0f);
				m_pCheckBoxLeft->setTabOrder(1);
				m_pCheckBoxLeft->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxLeft->setCaption(UTF8ToString(""));
				m_pCheckBoxLeft->setAutoSize(false);

				m_pCheckBoxTop->setName(L"CheckBoxTop");
				m_pCheckBoxTop->getTransform()->Translate(77.0f, 11.0f, 0.0f);
				m_pCheckBoxTop->setTabOrder(2);
				m_pCheckBoxTop->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxTop->setCaption(UTF8ToString(""));
				m_pCheckBoxTop->setAutoSize(false);

				m_pCheckBoxRight->setName(L"CheckBoxRight");
				m_pCheckBoxRight->getTransform()->Translate(142.0f, 43.0f, 0.0f);
				m_pCheckBoxRight->setTabOrder(3);
				m_pCheckBoxRight->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxRight->setCaption(UTF8ToString(""));
				m_pCheckBoxRight->setAutoSize(false);

				m_pCheckBoxBottom->setName(L"CheckBoxBottom");
				m_pCheckBoxBottom->getTransform()->Translate(77.0f, 72.0f, 0.0f);
				m_pCheckBoxBottom->setTabOrder(4);
				m_pCheckBoxBottom->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxBottom->setCaption(UTF8ToString(""));
				m_pCheckBoxBottom->setAutoSize(false);

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(13.0f, 92.0f, 0.0f);
				m_pButtonOk->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonOk->setTabOrder(5);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { parent<IDialogBoxRectBProto*, false>(sender)->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(85.0f, 92.0f, 0.0f);
				m_pButtonCancel->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonCancel->setTabOrder(6);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { parent<IDialogBoxRectBProto*, false>(sender)->ButtonCancel_OnClick(sender); };


			}

		public:
			IDialogBoxRectBProto(const String &class_name, const bool accept_form, const bool accept_control, const bool accept_focus, const bool tab_stop, const Point &design_dpi = DesignDPI, IDialogBoxService *service = nullptr) :
				CDialogBoxEx(class_name, accept_form, accept_control, accept_focus, tab_stop, design_dpi, service ? service : new IDialogBoxRectBProtoService(this)),
				m_pCheckBoxLeft{ nullptr },
				m_pCheckBoxTop{ nullptr },
				m_pCheckBoxRight{ nullptr },
				m_pCheckBoxBottom{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr }
			{
				CLockRepaint lock(this);
				setName(L"DialogBoxRectBProto");
				setCaption(UTF8ToString("Enable borders"));
				setClientSize(Point{ 166, 123 });
				setWindowPosition(WindowPosition::MainFormCenter);
				setState(WindowState::Hidden);
				setHasMaximizeBox(false);
				setHasMinimizeBox(false);
				setHasSizeBox(false);
				Initialize();
				OnPaint = [](IControl *sender, const MessagePaint &m, bool &draw_children)->void { cast<IDialogBoxRectBProto*>(sender)->FormRectBProto_OnPaint(sender, m, draw_children); };
				OnKeyUp = [](IControl *sender, const MessageKey &m, bool &processed)->void { cast<IDialogBoxRectBProto*>(sender)->FormRectBProto_OnKeyUp(sender, m, processed); };
			}

			IComponent *getComponent(const String &name)
			{
				return nullptr;
			}

			IControl *FindControl(const String &name, IControl *exclude = nullptr) override
			{
				if (name == L"CheckBoxLeft" && m_pCheckBoxLeft != exclude)
					return m_pCheckBoxLeft;
				if (name == L"CheckBoxTop" && m_pCheckBoxTop != exclude)
					return m_pCheckBoxTop;
				if (name == L"CheckBoxRight" && m_pCheckBoxRight != exclude)
					return m_pCheckBoxRight;
				if (name == L"CheckBoxBottom" && m_pCheckBoxBottom != exclude)
					return m_pCheckBoxBottom;
				if (name == L"ButtonOk" && m_pButtonOk != exclude)
					return m_pButtonOk;
				if (name == L"ButtonCancel" && m_pButtonCancel != exclude)
					return m_pButtonCancel;
				return nullptr;
			}

		};
	}
}

