// This file was generated by Form Builder from Nitisa C++ GUI framework
// Framework site: http://nitisa.com
// Framework download: http://nitisa.com/downloads
// Framework documentation: http://nitisa.com/documentation
// Framework license: http://nitisa.com/site/license
// Form Builder version: 13.0.0
// Form Builder documentation: http://nitisa.com/guide/form-builder
// Generated: 2022-04-17 13:36:03

// !!! ATTENTION !!!
// This is an auto-generated file with form declaration and initialization.
// Include it into your form class header file and derive your form from the class implemented here.
// Add constructor and implement event processing methods(if exist) from "protected" section.
// For example:
//     FormRectBProto.h:
//         #include "IFormRectBProto.h" // Include this file
//
//         namespace nitisa
//         {
//             class IControl;
//
//             namespace standard
//             {
//                 class CFormRectBProto : public IFormRectBProto // Derive your form from class from this file
//                 {
//                 protected: // Declare overridden methods handling events if there ones in this class
//                     void ButtonAdd_OnClick(IControl *sender) override;
//                 public:
//                     CFormRectBProto(); // Declare constructor
//                 };
//             }
//         }
//
//     FormRectBProto.cpp:
//         #include "Standard/Platform/Windows/Window.h" // Include required platform window management class
//         #include "Standard/Platform/Windows/OpenGL/Renderer.h" // Include required renderer
//         #include "FormRectBProto.h" // Include header class of your form
//
//         namespace nitisa
//         {
//             namespace standard
//             {
//                 CFormRectBProto::CFormRectBProto(): // Implement constructor of your form
//                     IFormRectBProto(new standard::windows::CWindow(), new standard::windows::opengl::CRenderer(false, 0))
//                 {
//                     // Insert your code here
//                 }
//
//                 void CFormRectBProto::ButtonAdd_OnClick(IControl *sender) // Implement event processing methods
//                 {
//                     // Insert your code here
//                 }
//             }
//         }


#pragma once

#include "Nitisa/Core/Form.h"
#include "Nitisa/Core/LockRepaint.h"
#include "Nitisa/Core/Messages.h"
#include "Nitisa/Core/RotateOrder.h"
#include "Nitisa/Core/Strings.h"
#include "Nitisa/Core/TransformOrder.h"
#include "Nitisa/Core/Utils.h"
#include "Nitisa/Core/WindowPosition.h"
#include "Nitisa/Core/WindowState.h"
#include "Nitisa/Interfaces/IApplication.h"
#include "Nitisa/Interfaces/IApplicationService.h"
#include "Nitisa/Interfaces/IFormService.h"
#include "Nitisa/Interfaces/ITransform.h"
#include "Nitisa/Math/Point.h"
#include "Nitisa/Math/PointF.h"
#include "Nitisa/Math/Transform.h"
#include "../../Controls/Button/Button.h"
#include "../../Controls/CheckBox/CheckBox.h"

namespace nitisa
{
	class IControl;
	class IForm;
	class IRenderer;
	class IWindow;
	struct CreateParams;

	namespace standard
	{
		class IFormRectBProto : public CForm
		{
		protected:
			// Controls
			CCheckBox *m_pCheckBoxLeft;
			CCheckBox *m_pCheckBoxTop;
			CCheckBox *m_pCheckBoxRight;
			CCheckBox *m_pCheckBoxBottom;
			CButton *m_pButtonOk;
			CButton *m_pButtonCancel;

		protected:
			// Events(Should be implemented in derived widget)
			virtual void FormRectBProto_OnPaint(IForm *sender, const MessagePaint &m, bool &draw_children) = 0;
			virtual void FormRectBProto_OnKeyUp(IForm *sender, const MessageKey &m) = 0;
			virtual void ButtonOk_OnClick(IControl *sender) = 0;
			virtual void ButtonCancel_OnClick(IControl *sender) = 0;

		private:
			void Initialize()
			{
				// Create controls
				m_pCheckBoxLeft = new CCheckBox(this);
				m_pCheckBoxLeft->setName(L"CheckBoxLeft");
				m_pCheckBoxTop = new CCheckBox(this);
				m_pCheckBoxTop->setName(L"CheckBoxTop");
				m_pCheckBoxRight = new CCheckBox(this);
				m_pCheckBoxRight->setName(L"CheckBoxRight");
				m_pCheckBoxBottom = new CCheckBox(this);
				m_pCheckBoxBottom->setName(L"CheckBoxBottom");
				m_pButtonOk = new CButton(this);
				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonCancel = new CButton(this);
				m_pButtonCancel->setName(L"ButtonCancel");

				// Initialize controls
				m_pCheckBoxLeft->setName(L"CheckBoxLeft");
				m_pCheckBoxLeft->getTransform()->Translate(11.0f, 43.0f, 0.0f);
				m_pCheckBoxLeft->setTabOrder(1);
				m_pCheckBoxLeft->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxLeft->setCaption(UTF8ToString(""));
				m_pCheckBoxLeft->setAutoSize(false);

				m_pCheckBoxTop->setName(L"CheckBoxTop");
				m_pCheckBoxTop->getTransform()->Translate(77.0f, 11.0f, 0.0f);
				m_pCheckBoxTop->setTabOrder(2);
				m_pCheckBoxTop->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxTop->setCaption(UTF8ToString(""));
				m_pCheckBoxTop->setAutoSize(false);

				m_pCheckBoxRight->setName(L"CheckBoxRight");
				m_pCheckBoxRight->getTransform()->Translate(142.0f, 43.0f, 0.0f);
				m_pCheckBoxRight->setTabOrder(3);
				m_pCheckBoxRight->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxRight->setCaption(UTF8ToString(""));
				m_pCheckBoxRight->setAutoSize(false);

				m_pCheckBoxBottom->setName(L"CheckBoxBottom");
				m_pCheckBoxBottom->getTransform()->Translate(77.0f, 72.0f, 0.0f);
				m_pCheckBoxBottom->setTabOrder(4);
				m_pCheckBoxBottom->setSize(PointF{ 14.0f, 14.0f });
				m_pCheckBoxBottom->setCaption(UTF8ToString(""));
				m_pCheckBoxBottom->setAutoSize(false);

				m_pButtonOk->setName(L"ButtonOk");
				m_pButtonOk->getTransform()->Translate(13.0f, 92.0f, 0.0f);
				m_pButtonOk->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonOk->setTabOrder(5);
				m_pButtonOk->setCaption(UTF8ToString("OK"));
				m_pButtonOk->OnClick = [](IControl *sender)->void { cast<IFormRectBProto*>(sender->getForm())->ButtonOk_OnClick(sender); };

				m_pButtonCancel->setName(L"ButtonCancel");
				m_pButtonCancel->getTransform()->Translate(85.0f, 92.0f, 0.0f);
				m_pButtonCancel->setSize(PointF{ 68.0f, 23.0f });
				m_pButtonCancel->setTabOrder(6);
				m_pButtonCancel->setCaption(UTF8ToString("Cancel"));
				m_pButtonCancel->OnClick = [](IControl *sender)->void { cast<IFormRectBProto*>(sender->getForm())->ButtonCancel_OnClick(sender); };


			}

		public:
			IFormRectBProto(IWindow *window, IRenderer *renderer, const String &class_name = L"FormRectBProto", const CreateParams *params = nullptr) :
				CForm(class_name, nullptr, renderer, params),
				m_pCheckBoxLeft{ nullptr },
				m_pCheckBoxTop{ nullptr },
				m_pCheckBoxRight{ nullptr },
				m_pCheckBoxBottom{ nullptr },
				m_pButtonOk{ nullptr },
				m_pButtonCancel{ nullptr }
			{
				if (window)
				{
					CLockRepaint lock(this);
					setName(L"FormRectBProto");
					setCaption(UTF8ToString("Enable borders"));
					setClientSize(Point{ 166, 123 });
					setState(WindowState::Hidden);
					setWindowPosition(WindowPosition::MainFormCenter);
					setHasMaximizeBox(false);
					setHasMinimizeBox(false);
					setHasSizeBox(false);
					QueryService()->setWindow(window);
					Application->QueryService()->Add(this);
					Initialize();
					Repaint(Rect{ 0, 0, 0, 0 }, true);
					OnPaint = [](IForm *sender, const MessagePaint &m, bool &draw_children)->void { cast<IFormRectBProto*>(sender)->FormRectBProto_OnPaint(sender, m, draw_children); };
					OnKeyUp = [](IForm *sender, const MessageKey &m)->void { cast<IFormRectBProto*>(sender)->FormRectBProto_OnKeyUp(sender, m); };
				}
			}
		};
	}
}
