#pragma once

#include "IFormMain.h" // Include form file generated by Form Builder

namespace nitisa
{
	namespace app
	{
		class CFormMain :public IFormMain // Class declaration for application's form
		{
		private:
			int m_iLastId; // Variable for storing last received message id
		protected:
			// Event processing methods copied from IFormMain and declared as overrided
			void ButtonConnect_OnClick(IControl *sender) override;
			void ButtonDisconnect_OnClick(IControl *sender) override;
			void Timer_OnTimer(IComponent *sender) override;
			void EditMessage_OnKeyUp(IControl *sender, const MessageKey &m, bool &processed) override;
		public:
			CFormMain(); // Constructor
		};
	}
}